SPECIES_TREECKO = "Treecko"
SPECIES_GROVYLE = "Grovyle"
SPECIES_SCEPTILE = "Sceptile"
SPECIES_TORCHIC = "Torchic"
SPECIES_COMBUSKEN = "Combusken"
SPECIES_BLAZIKEN = "Blaziken"
SPECIES_MUDKIP = "Mudkip"
SPECIES_MARSHTOMP = "Marshtomp"
SPECIES_SWAMPERT = "Swampert"
SPECIES_POOCHYENA = "Poochyena"
SPECIES_MIGHTYENA = "Mightyena"
SPECIES_ZIGZAGOON = "Zigzagoon"
SPECIES_LINOONE = "Linoone"
SPECIES_WURMPLE = "Wurmple"
SPECIES_SILCOON = "Silcoon"
SPECIES_BEAUTIFLY = "Beautifly"
SPECIES_CASCOON = "Cascoon"
SPECIES_DUSTOX = "Dustox"
SPECIES_LOTAD = "Lotad"
SPECIES_LOMBRE = "Lombre"
SPECIES_LUDICOLO = "Ludicolo"
SPECIES_SEEDOT = "Seedot"
SPECIES_NUZLEAF = "Nuzleaf"
SPECIES_SHIFTRY = "Shiftry"
SPECIES_TAILLOW = "Taillow"
SPECIES_SWELLOW = "Swellow"
SPECIES_WINGULL = "Wingull"
SPECIES_PELIPPER = "Pelipper"
SPECIES_RALTS = "Ralts"
SPECIES_KIRLIA = "Kirlia"
SPECIES_GARDEVOIR = "Gardevoir"
SPECIES_SURSKIT = "Surskit"
SPECIES_MASQUERAIN = "Masquerain"
SPECIES_SHROOMISH = "Shroomish"
SPECIES_BRELOOM = "Breloom"
SPECIES_SLAKOTH = "Slakoth"
SPECIES_VIGOROTH = "Vigoroth"
SPECIES_SLAKING = "Slaking"
SPECIES_ABRA = "Abra"
SPECIES_KADABRA = "Kadabra"
SPECIES_ALAKAZAM = "Alakazam"
SPECIES_NINCADA = "Nincada"
SPECIES_NINJASK = "Ninjask"
SPECIES_SHEDINJA = "Shedinja"
SPECIES_WHISMUR = "Whismur"
SPECIES_LOUDRED = "Loudred"
SPECIES_EXPLOUD = "Exploud"
SPECIES_MAKUHITA = "Makuhita"
SPECIES_HARIYAMA = "Hariyama"
SPECIES_GOLDEEN = "Goldeen"
SPECIES_SEAKING = "Seaking"
SPECIES_MAGIKARP = "Magikarp"
SPECIES_GYARADOS = "Gyarados"
SPECIES_AZURILL = "Azurill"
SPECIES_MARILL = "Marill"
SPECIES_AZUMARILL = "Azumarill"
SPECIES_GEODUDE = "Geodude"
SPECIES_GRAVELER = "Graveler"
SPECIES_GOLEM = "Golem"
SPECIES_NOSEPASS = "Nosepass"
SPECIES_SKITTY = "Skitty"
SPECIES_DELCATTY = "Delcatty"
SPECIES_ZUBAT = "Zubat"
SPECIES_GOLBAT = "Golbat"
SPECIES_CROBAT = "Crobat"
SPECIES_TENTACOOL = "Tentacool"
SPECIES_TENTACRUEL = "Tentacruel"
SPECIES_SABLEYE = "Sableye"
SPECIES_MAWILE = "Mawile"
SPECIES_ARON = "Aron"
SPECIES_LAIRON = "Lairon"
SPECIES_AGGRON = "Aggron"
SPECIES_MACHOP = "Machop"
SPECIES_MACHOKE = "Machoke"
SPECIES_MACHAMP = "Machamp"
SPECIES_MEDITITE = "Meditite"
SPECIES_MEDICHAM = "Medicham"
SPECIES_ELECTRIKE = "Electrike"
SPECIES_MANECTRIC = "Manectric"
SPECIES_PLUSLE = "Plusle"
SPECIES_MINUN = "Minun"
SPECIES_MAGNEMITE = "Magnemite"
SPECIES_MAGNETON = "Magneton"
SPECIES_VOLTORB = "Voltorb"
SPECIES_ELECTRODE = "Electrode"
SPECIES_VOLBEAT = "Volbeat"
SPECIES_ILLUMISE = "Illumise"
SPECIES_ODDISH = "Oddish"
SPECIES_GLOOM = "Gloom"
SPECIES_VILEPLUME = "Vileplume"
SPECIES_BELLOSSOM = "Bellossom"
SPECIES_DODUO = "Doduo"
SPECIES_DODRIO = "Dodrio"
SPECIES_ROSELIA = "Roselia"
SPECIES_GULPIN = "Gulpin"
SPECIES_SWALOT = "Swalot"
SPECIES_CARVANHA = "Carvanha"
SPECIES_SHARPEDO = "Sharpedo"
SPECIES_WAILMER = "Wailmer"
SPECIES_WAILORD = "Wailord"
SPECIES_NUMEL = "Numel"
SPECIES_CAMERUPT = "Camerupt"
SPECIES_SLUGMA = "Slugma"
SPECIES_MAGCARGO = "Magcargo"
SPECIES_TORKOAL = "Torkoal"
SPECIES_GRIMER = "Grimer"
SPECIES_MUK = "Muk"
SPECIES_KOFFING = "Koffing"
SPECIES_WEEZING = "Weezing"
SPECIES_SPOINK = "Spoink"
SPECIES_GRUMPIG = "Grumpig"
SPECIES_SANDSHREW = "Sandshrew"
SPECIES_SANDSLASH = "Sandslash"
SPECIES_SPINDA = "Spinda"
SPECIES_SKARMORY = "Skarmory"
SPECIES_TRAPINCH = "Trapinch"
SPECIES_VIBRAVA = "Vibrava"
SPECIES_FLYGON = "Flygon"
SPECIES_CACNEA = "Cacnea"
SPECIES_CACTURNE = "Cacturne"
SPECIES_SWABLU = "Swablu"
SPECIES_ALTARIA = "Altaria"
SPECIES_ZANGOOSE = "Zangoose"
SPECIES_SEVIPER = "Seviper"
SPECIES_LUNATONE = "Lunatone"
SPECIES_SOLROCK = "Solrock"
SPECIES_BARBOACH = "Barboach"
SPECIES_WHISCASH = "Whiscash"
SPECIES_CORPHISH = "Corphish"
SPECIES_CRAWDAUNT = "Crawdaunt"
SPECIES_BALTOY = "Baltoy"
SPECIES_CLAYDOL = "Claydol"
SPECIES_LILEEP = "Lileep"
SPECIES_CRADILY = "Cradily"
SPECIES_ANORITH = "Anorith"
SPECIES_ARMALDO = "Armaldo"
SPECIES_IGGLYBUFF = "Igglybuff"
SPECIES_JIGGLYPUFF = "Jigglypuff"
SPECIES_WIGGLYTUFF = "Wigglytuff"
SPECIES_FEEBAS = "Feebas"
SPECIES_MILOTIC = "Milotic"
SPECIES_CASTFORM = "Castform"
SPECIES_STARYU = "Staryu"
SPECIES_STARMIE = "Starmie"
SPECIES_KECLEON = "Kecleon"
SPECIES_SHUPPET = "Shuppet"
SPECIES_BANETTE = "Banette"
SPECIES_DUSKULL = "Duskull"
SPECIES_DUSCLOPS = "Dusclops"
SPECIES_TROPIUS = "Tropius"
SPECIES_CHIMECHO = "Chimecho"
SPECIES_ABSOL = "Absol"
SPECIES_VULPIX = "Vulpix"
SPECIES_NINETALES = "Ninetales"
SPECIES_PICHU = "Pichu"
SPECIES_PIKACHU = "Pikachu"
SPECIES_RAICHU = "Raichu"
SPECIES_PSYDUCK = "Psyduck"
SPECIES_GOLDUCK = "Golduck"
SPECIES_WYNAUT = "Wynaut"
SPECIES_WOBBUFFET = "Wobbuffet"
SPECIES_NATU = "Natu"
SPECIES_XATU = "Xatu"
SPECIES_GIRAFARIG = "Girafarig"
SPECIES_PHANPY = "Phanpy"
SPECIES_DONPHAN = "Donphan"
SPECIES_PINSIR = "Pinsir"
SPECIES_HERACROSS = "Heracross"
SPECIES_RHYHORN = "Rhyhorn"
SPECIES_RHYDON = "Rhydon"
SPECIES_SNORUNT = "Snorunt"
SPECIES_GLALIE = "Glalie"
SPECIES_SPHEAL = "Spheal"
SPECIES_SEALEO = "Sealeo"
SPECIES_WALREIN = "Walrein"
SPECIES_CLAMPERL = "Clamperl"
SPECIES_HUNTAIL = "Huntail"
SPECIES_GOREBYSS = "Gorebyss"
SPECIES_RELICANTH = "Relicanth"
SPECIES_CORSOLA = "Corsola"
SPECIES_CHINCHOU = "Chinchou"
SPECIES_LANTURN = "Lanturn"
SPECIES_LUVDISC = "Luvdisc"
SPECIES_HORSEA = "Horsea"
SPECIES_SEADRA = "Seadra"
SPECIES_KINGDRA = "Kingdra"
SPECIES_BAGON = "Bagon"
SPECIES_SHELGON = "Shelgon"
SPECIES_SALAMENCE = "Salamence"
SPECIES_BELDUM = "Beldum"
SPECIES_METANG = "Metang"
SPECIES_METAGROSS = "Metagross"
SPECIES_REGIROCK = "Regirock"
SPECIES_REGICE = "Regice"
SPECIES_REGISTEEL = "Registeel"
SPECIES_LATIAS = "Latias"
SPECIES_LATIOS = "Latios"
SPECIES_KYOGRE = "Kyogre"
SPECIES_GROUDON = "Groudon"
SPECIES_RAYQUAZA = "Rayquaza"
SPECIES_JIRACHI = "Jirachi"
SPECIES_CHIKORITA = "Chikorita"
SPECIES_CYNDAQUIL = "Cyndaquil"
SPECIES_TOTODILE = "Totodile"
SPECIES_AERODACTYL = "Aerodactyl"

# Bonus Stage Clears
BONUS_DUSCLOPS = "Dusclops Bonus Stage - Complete"
BONUS_KECLEON = "Kecleon Bonus Stage - Complete"
BONUS_KYOGRE = "Kyogre Bonus Stage - Complete"
BONUS_GROUDON = "Groudon Bonus Stage - Complete"
BONUS_RAYQUAZA = "Rayquaza Bonus Stage - Complete"

# Items
EXTRA_STARTING_LIFE = "Extra Starting Ball"
STARTING_BALL_MODIFIER = "Progressive Starting Ball Modifier"
STARTING_COINS = "+10 Starting Coins"
PICHU_UPGRADE = "Permanent Pichu"
SPECIAL_GUESTS = "eReader Card - Special Guests"
ENCOUNTER_RATE_UP = "eReader Card - Encounter Rate Up"
DX_MODE = "eReader Card - DX Mode"  # Not going to use, we want to hijack it for randomization
RUINS_AREA_CARD = "eReader Card - Ruins Area"
RUBY_BOARD = "Ruby Board"
SAPPHIRE_BOARD = "Sapphire Board"
EVO_ARROW = "Evo Arrow"
GET_ARROW = "Get Arrow"
# HATCH_MODE = "Hatch Mode"
CHIKORITA_DEX = "Chikorita Pokédex Entry"
CYNDAQUIL_DEX = "Cyndaquil Pokédex Entry"
TOTODILE_DEX = "Totodile Pokédex Entry"
AERODACTYL_DEX = "Aerodactyl Pokédex Entry"
EGG_BUNCH_1 = "Egg Bunch 1"
EGG_BUNCH_2 = "Egg Bunch 2"
EGG_BUNCH_3 = "Egg Bunch 3"
EGG_BUNCH_4 = "Egg Bunch 4"
EGG_BUNCH_RUBY = "Egg Bunch (Ruby)"
EGG_BUNCH_SAPPHIRE = "Egg Bunch (Sapphire)"
# Areas
FOREST_RUBY = "Forest (Ruby)"
VOLCANO_RUBY = "Volcano (Ruby)"
PLAINS_RUBY = "Plains (Ruby)"
OCEAN_RUBY = "Ocean (Ruby)"
SAFARI_ZONE_RUBY = "Safari Zone (Ruby)"
CAVE_RUBY = "Cave (Ruby)"
RUINS_RUBY = "Ruins (Ruby)"
FOREST_SAPPHIRE = "Forest (Sapphire)"
LAKE_SAPPHIRE = "Lake (Sapphire)"
PLAINS_SAPPHIRE = "Plains (Sapphire)"
WILDERNESS_SAPPHIRE = "Wilderness (Sapphire)"
OCEAN_SAPPHIRE = "Ocean (Sapphire)"
CAVE_SAPPHIRE = "Cave (Sapphire)"
RUINS_SAPPHIRE = "Ruins (Sapphire)"
# Filler
EXTRA_BALL = "Extra Ball"
BIG = "BIG"
SMALL = "Small"
BALL_SAVER = "30 Sec. Ball Saver"

POKEDEX: dict[str, int] = {
    SPECIES_TREECKO: 0,
    SPECIES_GROVYLE: 1,
    SPECIES_SCEPTILE: 2,
    SPECIES_TORCHIC: 3,
    SPECIES_COMBUSKEN: 4,
    SPECIES_BLAZIKEN: 5,
    SPECIES_MUDKIP: 6,
    SPECIES_MARSHTOMP: 7,
    SPECIES_SWAMPERT: 8,
    SPECIES_POOCHYENA: 9,
    SPECIES_MIGHTYENA: 10,
    SPECIES_ZIGZAGOON: 11,
    SPECIES_LINOONE: 12,
    SPECIES_WURMPLE: 13,
    SPECIES_SILCOON: 14,
    SPECIES_BEAUTIFLY: 15,
    SPECIES_CASCOON: 16,
    SPECIES_DUSTOX: 17,
    SPECIES_LOTAD: 18,
    SPECIES_LOMBRE: 19,
    SPECIES_LUDICOLO: 20,
    SPECIES_SEEDOT: 21,
    SPECIES_NUZLEAF: 22,
    SPECIES_SHIFTRY: 23,
    SPECIES_TAILLOW: 24,
    SPECIES_SWELLOW: 25,
    SPECIES_WINGULL: 26,
    SPECIES_PELIPPER: 27,
    SPECIES_RALTS: 28,
    SPECIES_KIRLIA: 29,
    SPECIES_GARDEVOIR: 30,
    SPECIES_SURSKIT: 31,
    SPECIES_MASQUERAIN: 32,
    SPECIES_SHROOMISH: 33,
    SPECIES_BRELOOM: 34,
    SPECIES_SLAKOTH: 35,
    SPECIES_VIGOROTH: 36,
    SPECIES_SLAKING: 37,
    SPECIES_ABRA: 38,
    SPECIES_KADABRA: 39,
    SPECIES_ALAKAZAM: 40,
    SPECIES_NINCADA: 41,
    SPECIES_NINJASK: 42,
    SPECIES_SHEDINJA: 43,
    SPECIES_WHISMUR: 44,
    SPECIES_LOUDRED: 45,
    SPECIES_EXPLOUD: 46,
    SPECIES_MAKUHITA: 47,
    SPECIES_HARIYAMA: 48,
    SPECIES_GOLDEEN: 49,
    SPECIES_SEAKING: 50,
    SPECIES_MAGIKARP: 51,
    SPECIES_GYARADOS: 52,
    SPECIES_AZURILL: 53,
    SPECIES_MARILL: 54,
    SPECIES_AZUMARILL: 55,
    SPECIES_GEODUDE: 56,
    SPECIES_GRAVELER: 57,
    SPECIES_GOLEM: 58,
    SPECIES_NOSEPASS: 59,
    SPECIES_SKITTY: 60,
    SPECIES_DELCATTY: 61,
    SPECIES_ZUBAT: 62,
    SPECIES_GOLBAT: 63,
    SPECIES_CROBAT: 64,
    SPECIES_TENTACOOL: 65,
    SPECIES_TENTACRUEL: 66,
    SPECIES_SABLEYE: 67,
    SPECIES_MAWILE: 68,
    SPECIES_ARON: 69,
    SPECIES_LAIRON: 70,
    SPECIES_AGGRON: 71,
    SPECIES_MACHOP: 72,
    SPECIES_MACHOKE: 73,
    SPECIES_MACHAMP: 74,
    SPECIES_MEDITITE: 75,
    SPECIES_MEDICHAM: 76,
    SPECIES_ELECTRIKE: 77,
    SPECIES_MANECTRIC: 78,
    SPECIES_PLUSLE: 79,
    SPECIES_MINUN: 80,
    SPECIES_MAGNEMITE: 81,
    SPECIES_MAGNETON: 82,
    SPECIES_VOLTORB: 83,
    SPECIES_ELECTRODE: 84,
    SPECIES_VOLBEAT: 85,
    SPECIES_ILLUMISE: 86,
    SPECIES_ODDISH: 87,
    SPECIES_GLOOM: 88,
    SPECIES_VILEPLUME: 89,
    SPECIES_BELLOSSOM: 90,
    SPECIES_DODUO: 91,
    SPECIES_DODRIO: 92,
    SPECIES_ROSELIA: 93,
    SPECIES_GULPIN: 94,
    SPECIES_SWALOT: 95,
    SPECIES_CARVANHA: 96,
    SPECIES_SHARPEDO: 97,
    SPECIES_WAILMER: 98,
    SPECIES_WAILORD: 99,
    SPECIES_NUMEL: 100,
    SPECIES_CAMERUPT: 101,
    SPECIES_SLUGMA: 102,
    SPECIES_MAGCARGO: 103,
    SPECIES_TORKOAL: 104,
    SPECIES_GRIMER: 105,
    SPECIES_MUK: 106,
    SPECIES_KOFFING: 107,
    SPECIES_WEEZING: 108,
    SPECIES_SPOINK: 109,
    SPECIES_GRUMPIG: 110,
    SPECIES_SANDSHREW: 111,
    SPECIES_SANDSLASH: 112,
    SPECIES_SPINDA: 113,
    SPECIES_SKARMORY: 114,
    SPECIES_TRAPINCH: 115,
    SPECIES_VIBRAVA: 116,
    SPECIES_FLYGON: 117,
    SPECIES_CACNEA: 118,
    SPECIES_CACTURNE: 119,
    SPECIES_SWABLU: 120,
    SPECIES_ALTARIA: 121,
    SPECIES_ZANGOOSE: 122,
    SPECIES_SEVIPER: 123,
    SPECIES_LUNATONE: 124,
    SPECIES_SOLROCK: 125,
    SPECIES_BARBOACH: 126,
    SPECIES_WHISCASH: 127,
    SPECIES_CORPHISH: 128,
    SPECIES_CRAWDAUNT: 129,
    SPECIES_BALTOY: 130,
    SPECIES_CLAYDOL: 131,
    SPECIES_LILEEP: 132,
    SPECIES_CRADILY: 133,
    SPECIES_ANORITH: 134,
    SPECIES_ARMALDO: 135,
    SPECIES_IGGLYBUFF: 136,
    SPECIES_JIGGLYPUFF: 137,
    SPECIES_WIGGLYTUFF: 138,
    SPECIES_FEEBAS: 139,
    SPECIES_MILOTIC: 140,
    SPECIES_CASTFORM: 141,
    SPECIES_STARYU: 142,
    SPECIES_STARMIE: 143,
    SPECIES_KECLEON: 144,
    SPECIES_SHUPPET: 145,
    SPECIES_BANETTE: 146,
    SPECIES_DUSKULL: 147,
    SPECIES_DUSCLOPS: 148,
    SPECIES_TROPIUS: 149,
    SPECIES_CHIMECHO: 150,
    SPECIES_ABSOL: 151,
    SPECIES_VULPIX: 152,
    SPECIES_NINETALES: 153,
    SPECIES_PICHU: 154,
    SPECIES_PIKACHU: 155,
    SPECIES_RAICHU: 156,
    SPECIES_PSYDUCK: 157,
    SPECIES_GOLDUCK: 158,
    SPECIES_WYNAUT: 159,
    SPECIES_WOBBUFFET: 160,
    SPECIES_NATU: 161,
    SPECIES_XATU: 162,
    SPECIES_GIRAFARIG: 163,
    SPECIES_PHANPY: 164,
    SPECIES_DONPHAN: 165,
    SPECIES_PINSIR: 166,
    SPECIES_HERACROSS: 167,
    SPECIES_RHYHORN: 168,
    SPECIES_RHYDON: 169,
    SPECIES_SNORUNT: 170,
    SPECIES_GLALIE: 171,
    SPECIES_SPHEAL: 172,
    SPECIES_SEALEO: 173,
    SPECIES_WALREIN: 174,
    SPECIES_CLAMPERL: 175,
    SPECIES_HUNTAIL: 176,
    SPECIES_GOREBYSS: 177,
    SPECIES_RELICANTH: 178,
    SPECIES_CORSOLA: 179,
    SPECIES_CHINCHOU: 180,
    SPECIES_LANTURN: 181,
    SPECIES_LUVDISC: 182,
    SPECIES_HORSEA: 183,
    SPECIES_SEADRA: 184,
    SPECIES_KINGDRA: 185,
    SPECIES_BAGON: 186,
    SPECIES_SHELGON: 187,
    SPECIES_SALAMENCE: 188,
    SPECIES_BELDUM: 189,
    SPECIES_METANG: 190,
    SPECIES_METAGROSS: 191,
    SPECIES_REGIROCK: 192,
    SPECIES_REGICE: 193,
    SPECIES_REGISTEEL: 194,
    SPECIES_LATIAS: 195,
    SPECIES_LATIOS: 196,
    SPECIES_KYOGRE: 197,
    SPECIES_GROUDON: 198,
    SPECIES_RAYQUAZA: 199,
    SPECIES_JIRACHI: 200,
    SPECIES_CHIKORITA: 201,
    SPECIES_CYNDAQUIL: 202,
    SPECIES_TOTODILE: 203,
    SPECIES_AERODACTYL: 204,
}

AREAS: dict[int, str] = {
    0: FOREST_RUBY,
    1: VOLCANO_RUBY,
    2: PLAINS_RUBY,
    3: OCEAN_RUBY,
    4: SAFARI_ZONE_RUBY,
    5: CAVE_RUBY,
    6: RUINS_RUBY,
    7: FOREST_SAPPHIRE,
    8: LAKE_SAPPHIRE,
    9: PLAINS_SAPPHIRE,
    10: OCEAN_SAPPHIRE,
    11: WILDERNESS_SAPPHIRE,
    12: CAVE_SAPPHIRE,
    13: RUINS_SAPPHIRE,
}

BONUS_STAGES: dict[int, str] = {
    0: BONUS_DUSCLOPS,
    1: BONUS_KECLEON,
    2: BONUS_KYOGRE,
    3: BONUS_GROUDON,
    4: BONUS_RAYQUAZA,
}

POKEDEX_INVERSE: dict[int, str] = {val: key for key, val in POKEDEX.items()}
