import typing
from BaseClasses import Item, ItemClassification
from .Regions import location_data, BASE_OFFSET

if typing.TYPE_CHECKING:
    from . import PokemonBW2World


class ItemData(typing.NamedTuple):
    code: typing.Optional[int]
    classification: ItemClassification
    quantity: int = 1
    skip_balancing: bool = False
    trap: bool = False


class PokemonBW2Item(Item):
    game = "Pokemon Black 2 and White 2"


all_items = {
    "Master Ball": ItemData(BASE_OFFSET+1, ItemClassification.filler),
    "Ultra Ball": ItemData(BASE_OFFSET+2, ItemClassification.filler, 5),
    "Great Ball": ItemData(BASE_OFFSET+3, ItemClassification.filler, 5),
    "Poke Ball": ItemData(BASE_OFFSET+4, ItemClassification.filler, 5),
    "Safari Ball": ItemData(BASE_OFFSET+5, ItemClassification.filler, 5),
    "Net Ball": ItemData(BASE_OFFSET+6, ItemClassification.filler, 5),
    "Dive Ball": ItemData(BASE_OFFSET+7, ItemClassification.filler, 5),
    "Nest Ball": ItemData(BASE_OFFSET+8, ItemClassification.filler, 5),
    "Repeat Ball": ItemData(BASE_OFFSET+9, ItemClassification.filler, 5),
    "Timer Ball": ItemData(BASE_OFFSET+10, ItemClassification.filler, 5),
    "Luxury Ball": ItemData(BASE_OFFSET+11, ItemClassification.filler, 5),
    "Premier Ball": ItemData(BASE_OFFSET+12, ItemClassification.filler, 5),
    "Dusk Ball": ItemData(BASE_OFFSET+13, ItemClassification.filler, 5),
    "Heal Ball": ItemData(BASE_OFFSET+14, ItemClassification.filler, 5),
    "Quick Ball": ItemData(BASE_OFFSET+15, ItemClassification.filler, 5),
    "Potion": ItemData(BASE_OFFSET+17, ItemClassification.filler),
    "Antidote": ItemData(BASE_OFFSET+18, ItemClassification.filler),
    "Burn Heal": ItemData(BASE_OFFSET+19, ItemClassification.filler),
    "Ice Heal": ItemData(BASE_OFFSET+20, ItemClassification.filler),
    "Awakening": ItemData(BASE_OFFSET+21, ItemClassification.filler),
    "Parlyz Heal": ItemData(BASE_OFFSET+22, ItemClassification.filler),
    "Full Restore": ItemData(BASE_OFFSET+23, ItemClassification.filler),
    "Max Potion": ItemData(BASE_OFFSET+24, ItemClassification.filler),
    "Hyper Potion": ItemData(BASE_OFFSET+25, ItemClassification.filler),
    "Super Potion": ItemData(BASE_OFFSET+26, ItemClassification.filler),
    "Full Heal": ItemData(BASE_OFFSET+27, ItemClassification.filler),
    "Revive": ItemData(BASE_OFFSET+28, ItemClassification.filler),
    "Max Revive": ItemData(BASE_OFFSET+29, ItemClassification.filler),
    "Fresh Water": ItemData(BASE_OFFSET+30, ItemClassification.filler),
    "Soda Pop": ItemData(BASE_OFFSET+31, ItemClassification.filler),
    "Lemonade": ItemData(BASE_OFFSET+32, ItemClassification.filler),
    "Moomoo Milk": ItemData(BASE_OFFSET+33, ItemClassification.filler),
    "EnergyPowder": ItemData(BASE_OFFSET+34, ItemClassification.filler),
    "Energy Root": ItemData(BASE_OFFSET+35, ItemClassification.filler),
    "Heal Powder": ItemData(BASE_OFFSET+36, ItemClassification.filler),
    "Revival Herb": ItemData(BASE_OFFSET+37, ItemClassification.filler),
    "Ether": ItemData(BASE_OFFSET+38, ItemClassification.filler),
    "Max Ether": ItemData(BASE_OFFSET+39, ItemClassification.filler),
    "Elixir": ItemData(BASE_OFFSET+40, ItemClassification.filler),
    "Max Elixir": ItemData(BASE_OFFSET+41, ItemClassification.filler),
    "Lava Cookie": ItemData(BASE_OFFSET+42, ItemClassification.filler),
    "Berry Juice": ItemData(BASE_OFFSET+43, ItemClassification.filler),
    "Sacred Ash": ItemData(BASE_OFFSET+44, ItemClassification.filler),
    "HP Up": ItemData(BASE_OFFSET+45, ItemClassification.filler),
    "Protein": ItemData(BASE_OFFSET+46, ItemClassification.filler),
    "Iron": ItemData(BASE_OFFSET+47, ItemClassification.filler),
    "Carbos": ItemData(BASE_OFFSET+48, ItemClassification.filler),
    "Calcium": ItemData(BASE_OFFSET+49, ItemClassification.filler),
    "Rare Candy": ItemData(BASE_OFFSET+50, ItemClassification.filler),
    "PP Up": ItemData(BASE_OFFSET+51, ItemClassification.filler),
    "Zinc": ItemData(BASE_OFFSET+52, ItemClassification.filler),
    "PP Max": ItemData(BASE_OFFSET+53, ItemClassification.filler),
    "Old Gateau": ItemData(BASE_OFFSET+54, ItemClassification.filler),
    "Guard Spec.": ItemData(BASE_OFFSET+55, ItemClassification.filler),
    "Dire Hit": ItemData(BASE_OFFSET+56, ItemClassification.filler),
    "X Attack": ItemData(BASE_OFFSET+57, ItemClassification.filler),
    "X Defend": ItemData(BASE_OFFSET+58, ItemClassification.filler),
    "X Speed": ItemData(BASE_OFFSET+59, ItemClassification.filler),
    "X Accuracy": ItemData(BASE_OFFSET+60, ItemClassification.filler),
    "X Special": ItemData(BASE_OFFSET+61, ItemClassification.filler),
    "X Sp. Def": ItemData(BASE_OFFSET+62, ItemClassification.filler),
    "Poke Doll": ItemData(BASE_OFFSET+63, ItemClassification.filler),
    "Fluffy Tail": ItemData(BASE_OFFSET+64, ItemClassification.filler),
    "Blue Flute": ItemData(BASE_OFFSET+65, ItemClassification.filler),
    "Yellow Flute": ItemData(BASE_OFFSET+66, ItemClassification.filler),
    "Red Flute": ItemData(BASE_OFFSET+67, ItemClassification.filler),
    "Black Flute": ItemData(BASE_OFFSET+68, ItemClassification.filler),
    "White Flute": ItemData(BASE_OFFSET+69, ItemClassification.filler),
    "Shoal Salt": ItemData(BASE_OFFSET+70, ItemClassification.filler),
    "Shoal Shell": ItemData(BASE_OFFSET+71, ItemClassification.filler),
    "Red Shard": ItemData(BASE_OFFSET+72, ItemClassification.filler),
    "Blue Shard": ItemData(BASE_OFFSET+73, ItemClassification.filler),
    "Yellow Shard": ItemData(BASE_OFFSET+74, ItemClassification.filler),
    "Green Shard": ItemData(BASE_OFFSET+75, ItemClassification.filler),
    "Super Repel": ItemData(BASE_OFFSET+76, ItemClassification.filler),
    "Max Repel": ItemData(BASE_OFFSET+77, ItemClassification.filler),
    "Escape Rope": ItemData(BASE_OFFSET+78, ItemClassification.filler),
    "Repel": ItemData(BASE_OFFSET+79, ItemClassification.filler),
    "Sun Stone": ItemData(BASE_OFFSET+80, ItemClassification.filler),
    "Moon Stone": ItemData(BASE_OFFSET+81, ItemClassification.filler),
    "Fire Stone": ItemData(BASE_OFFSET+82, ItemClassification.filler),
    "Thunderstone": ItemData(BASE_OFFSET+83, ItemClassification.filler),
    "Water Stone": ItemData(BASE_OFFSET+84, ItemClassification.filler),
    "Leaf Stone": ItemData(BASE_OFFSET+85, ItemClassification.filler),
    "TinyMushroom": ItemData(BASE_OFFSET+86, ItemClassification.filler),
    "Big Mushroom": ItemData(BASE_OFFSET+87, ItemClassification.filler),
    "Pearl": ItemData(BASE_OFFSET+88, ItemClassification.filler),
    "Big Pearl": ItemData(BASE_OFFSET+89, ItemClassification.filler),
    "Stardust": ItemData(BASE_OFFSET+90, ItemClassification.filler),
    "Star Piece": ItemData(BASE_OFFSET+91, ItemClassification.filler),
    "Nugget": ItemData(BASE_OFFSET+92, ItemClassification.filler),
    "Heart Scale": ItemData(BASE_OFFSET+93, ItemClassification.filler),
    "Honey": ItemData(BASE_OFFSET+94, ItemClassification.filler),
    "Growth Mulch": ItemData(BASE_OFFSET+95, ItemClassification.filler),
    "Damp Mulch": ItemData(BASE_OFFSET+96, ItemClassification.filler),
    "Stable Mulch": ItemData(BASE_OFFSET+97, ItemClassification.filler),
    "Gooey Mulch": ItemData(BASE_OFFSET+98, ItemClassification.filler),
    "Root Fossil": ItemData(BASE_OFFSET+99, ItemClassification.progression),
    "Claw Fossil": ItemData(BASE_OFFSET+100, ItemClassification.progression),
    "Helix Fossil": ItemData(BASE_OFFSET+101, ItemClassification.progression),
    "Dome Fossil": ItemData(BASE_OFFSET+102, ItemClassification.progression),
    "Old Amber": ItemData(BASE_OFFSET+103, ItemClassification.progression),
    "Armor Fossil": ItemData(BASE_OFFSET+104, ItemClassification.progression),
    "Skull Fossil": ItemData(BASE_OFFSET+105, ItemClassification.progression),
    "Rare Bone": ItemData(BASE_OFFSET+106, ItemClassification.filler),
    "Shiny Stone": ItemData(BASE_OFFSET+107, ItemClassification.progression),
    "Dusk Stone": ItemData(BASE_OFFSET+108, ItemClassification.progression),
    "Dawn Stone": ItemData(BASE_OFFSET+109, ItemClassification.progression),
    "Oval Stone": ItemData(BASE_OFFSET+110, ItemClassification.progression),
    "Griseous Orb": ItemData(BASE_OFFSET+112, ItemClassification.filler),
    # Reserve 113 for Archipelago Item
    "Douse Drive": ItemData(BASE_OFFSET+116, ItemClassification.filler),
    "Shock Drive": ItemData(BASE_OFFSET+117, ItemClassification.filler),
    "Burn Drive": ItemData(BASE_OFFSET+118, ItemClassification.filler),
    "Chill Drive": ItemData(BASE_OFFSET+119, ItemClassification.filler),
    "Basic Badge": ItemData(BASE_OFFSET+120, ItemClassification.progression),
    "Toxic Badge": ItemData(BASE_OFFSET+121, ItemClassification.progression),
    "Insect Badge": ItemData(BASE_OFFSET+122, ItemClassification.progression),
    "Bolt Badge": ItemData(BASE_OFFSET+123, ItemClassification.progression),
    "Quake Badge": ItemData(BASE_OFFSET+124, ItemClassification.progression),
    "Jet Badge": ItemData(BASE_OFFSET+125, ItemClassification.progression),
    "Legend Badge": ItemData(BASE_OFFSET+126, ItemClassification.progression),
    "Wave Badge": ItemData(BASE_OFFSET+127, ItemClassification.progression),
    "Sweet Heart": ItemData(BASE_OFFSET+134, ItemClassification.filler),
    "Adamant Orb": ItemData(BASE_OFFSET+135, ItemClassification.useful),
    "Lustrous Orb": ItemData(BASE_OFFSET+136, ItemClassification.useful),
    "Cheri Berry": ItemData(BASE_OFFSET+149, ItemClassification.filler, 5),
    "Chesto Berry": ItemData(BASE_OFFSET+150, ItemClassification.filler, 5),
    "Pecha Berry": ItemData(BASE_OFFSET+151, ItemClassification.filler, 5),
    "Rawst Berry": ItemData(BASE_OFFSET+152, ItemClassification.filler, 5),
    "Aspear Berry": ItemData(BASE_OFFSET+153, ItemClassification.filler, 5),
    "Leppa Berry": ItemData(BASE_OFFSET+154, ItemClassification.filler, 5),
    "Oran Berry": ItemData(BASE_OFFSET+155, ItemClassification.filler, 5),
    "Persim Berry": ItemData(BASE_OFFSET+156, ItemClassification.filler, 5),
    "Lum Berry": ItemData(BASE_OFFSET+157, ItemClassification.filler, 5),
    "Sitrus Berry": ItemData(BASE_OFFSET+158, ItemClassification.filler, 5),
    "Figy Berry": ItemData(BASE_OFFSET+159, ItemClassification.filler, 5),
    "Wiki Berry": ItemData(BASE_OFFSET+160, ItemClassification.filler, 5),
    "Mago Berry": ItemData(BASE_OFFSET+161, ItemClassification.filler, 5),
    "Aguav Berry": ItemData(BASE_OFFSET+162, ItemClassification.filler, 5),
    "Iapapa Berry": ItemData(BASE_OFFSET+163, ItemClassification.filler, 5),
    "Razz Berry": ItemData(BASE_OFFSET+164, ItemClassification.filler, 5),
    "Bluk Berry": ItemData(BASE_OFFSET+165, ItemClassification.filler, 5),
    "Nanab Berry": ItemData(BASE_OFFSET+166, ItemClassification.filler, 5),
    "Wepear Berry": ItemData(BASE_OFFSET+167, ItemClassification.filler, 5),
    "Pinap Berry": ItemData(BASE_OFFSET+168, ItemClassification.filler, 5),
    "Pomeg Berry": ItemData(BASE_OFFSET+169, ItemClassification.filler, 5),
    "Kelpsy Berry": ItemData(BASE_OFFSET+170, ItemClassification.filler, 5),
    "Qualot Berry": ItemData(BASE_OFFSET+171, ItemClassification.filler, 5),
    "Hondew Berry": ItemData(BASE_OFFSET+172, ItemClassification.filler, 5),
    "Grepa Berry": ItemData(BASE_OFFSET+173, ItemClassification.filler, 5),
    "Tamato Berry": ItemData(BASE_OFFSET+174, ItemClassification.filler, 5),
    "Cornn Berry": ItemData(BASE_OFFSET+175, ItemClassification.filler, 5),
    "Magost Berry": ItemData(BASE_OFFSET+176, ItemClassification.filler, 5),
    "Rabuta Berry": ItemData(BASE_OFFSET+177, ItemClassification.filler, 5),
    "Nomel Berry": ItemData(BASE_OFFSET+178, ItemClassification.filler, 5),
    "Spelon Berry": ItemData(BASE_OFFSET+179, ItemClassification.filler, 5),
    "Pamtre Berry": ItemData(BASE_OFFSET+180, ItemClassification.filler, 5),
    "Watmel Berry": ItemData(BASE_OFFSET+181, ItemClassification.filler, 5),
    "Durin Berry": ItemData(BASE_OFFSET+182, ItemClassification.filler, 5),
    "Belue Berry": ItemData(BASE_OFFSET+183, ItemClassification.filler, 5),
    "Occa Berry": ItemData(BASE_OFFSET+184, ItemClassification.filler, 5),
    "Passho Berry": ItemData(BASE_OFFSET+185, ItemClassification.filler, 5),
    "Wacan Berry": ItemData(BASE_OFFSET+186, ItemClassification.filler, 5),
    "Rindo Berry": ItemData(BASE_OFFSET+187, ItemClassification.filler, 5),
    "Yache Berry": ItemData(BASE_OFFSET+188, ItemClassification.filler, 5),
    "Chople Berry": ItemData(BASE_OFFSET+189, ItemClassification.filler, 5),
    "Kebia Berry": ItemData(BASE_OFFSET+190, ItemClassification.filler, 5),
    "Shuca Berry": ItemData(BASE_OFFSET+191, ItemClassification.filler, 5),
    "Coba Berry": ItemData(BASE_OFFSET+192, ItemClassification.filler, 5),
    "Payapa Berry": ItemData(BASE_OFFSET+193, ItemClassification.filler, 5),
    "Tanga Berry": ItemData(BASE_OFFSET+194, ItemClassification.filler, 5),
    "Charti Berry": ItemData(BASE_OFFSET+195, ItemClassification.filler, 5),
    "Kasib Berry": ItemData(BASE_OFFSET+196, ItemClassification.filler, 5),
    "Haban Berry": ItemData(BASE_OFFSET+197, ItemClassification.filler, 5),
    "Colbur Berry": ItemData(BASE_OFFSET+198, ItemClassification.filler, 5),
    "Babiri Berry": ItemData(BASE_OFFSET+199, ItemClassification.filler, 5),
    "Chilan Berry": ItemData(BASE_OFFSET+200, ItemClassification.filler, 5),
    "Liechi Berry": ItemData(BASE_OFFSET+201, ItemClassification.filler, 5),
    "Ganlon Berry": ItemData(BASE_OFFSET+202, ItemClassification.filler, 5),
    "Salac Berry": ItemData(BASE_OFFSET+203, ItemClassification.filler, 5),
    "Petaya Berry": ItemData(BASE_OFFSET+204, ItemClassification.filler, 5),
    "Apicot Berry": ItemData(BASE_OFFSET+205, ItemClassification.filler, 5),
    "Lansat Berry": ItemData(BASE_OFFSET+206, ItemClassification.filler, 5),
    "Starf Berry": ItemData(BASE_OFFSET+207, ItemClassification.filler, 5),
    "Enigma Berry": ItemData(BASE_OFFSET+208, ItemClassification.filler, 5),
    "Micle Berry": ItemData(BASE_OFFSET+209, ItemClassification.filler, 5),
    "Custap Berry": ItemData(BASE_OFFSET+210, ItemClassification.filler, 5),
    "Jaboca Berry": ItemData(BASE_OFFSET+211, ItemClassification.filler, 5),
    "Rowap Berry": ItemData(BASE_OFFSET+212, ItemClassification.filler, 5),
    "BrightPowder": ItemData(BASE_OFFSET+213, ItemClassification.useful),
    "White Herb": ItemData(BASE_OFFSET+214, ItemClassification.useful),
    "Macho Brace": ItemData(BASE_OFFSET+215, ItemClassification.useful),
    "Exp. Share": ItemData(BASE_OFFSET+216, ItemClassification.progression),
    "Quick Claw": ItemData(BASE_OFFSET+217, ItemClassification.useful),
    "Soothe Bell": ItemData(BASE_OFFSET+218, ItemClassification.useful),
    "Mental Herb": ItemData(BASE_OFFSET+219, ItemClassification.useful),
    "Choice Band": ItemData(BASE_OFFSET+220, ItemClassification.useful),
    "King's Rock": ItemData(BASE_OFFSET+221, ItemClassification.progression),
    "SilverPowder": ItemData(BASE_OFFSET+222, ItemClassification.useful),
    "Amulet Coin": ItemData(BASE_OFFSET+223, ItemClassification.useful),
    "Cleanse Tag": ItemData(BASE_OFFSET+224, ItemClassification.useful),
    "Soul Dew": ItemData(BASE_OFFSET+225, ItemClassification.useful),  # may change, depends if I wanna lock the Lati encounter here
    "DeepSeaTooth": ItemData(BASE_OFFSET+226, ItemClassification.progression),
    "DeepSeaScale": ItemData(BASE_OFFSET+227, ItemClassification.progression),
    "Smoke Ball": ItemData(BASE_OFFSET+228, ItemClassification.useful),
    "Everstone": ItemData(BASE_OFFSET+229, ItemClassification.useful),
    "Focus Band": ItemData(BASE_OFFSET+230, ItemClassification.useful),
    "Lucky Egg": ItemData(BASE_OFFSET+231, ItemClassification.useful),
    "Scope Lens": ItemData(BASE_OFFSET+232, ItemClassification.useful),
    "Metal Coat": ItemData(BASE_OFFSET+233, ItemClassification.progression),
    "Leftovers": ItemData(BASE_OFFSET+234, ItemClassification.useful),
    "Dragon Scale": ItemData(BASE_OFFSET+235, ItemClassification.progression),
    "Light Ball": ItemData(BASE_OFFSET+236, ItemClassification.useful),
    "Soft Sand": ItemData(BASE_OFFSET+237, ItemClassification.useful),
    "Hard Stone": ItemData(BASE_OFFSET+238, ItemClassification.useful),
    "Miracle Seed": ItemData(BASE_OFFSET+239, ItemClassification.useful),
    "BlackGlasses": ItemData(BASE_OFFSET+240, ItemClassification.useful),
    "Black Belt": ItemData(BASE_OFFSET+241, ItemClassification.useful),
    "Magnet": ItemData(BASE_OFFSET+242, ItemClassification.useful),
    "Mystic Water": ItemData(BASE_OFFSET+243, ItemClassification.useful),
    "Sharp Beak": ItemData(BASE_OFFSET+244, ItemClassification.useful),
    "Poison Barb": ItemData(BASE_OFFSET+245, ItemClassification.useful),
    "NeverMeltIce": ItemData(BASE_OFFSET+246, ItemClassification.useful),
    "Spell Tag": ItemData(BASE_OFFSET+247, ItemClassification.useful),
    "TwistedSpoon": ItemData(BASE_OFFSET+248, ItemClassification.useful),
    "Charcoal": ItemData(BASE_OFFSET+249, ItemClassification.useful),
    "Dragon Fang": ItemData(BASE_OFFSET+250, ItemClassification.useful),
    "Silk Scarf": ItemData(BASE_OFFSET+251, ItemClassification.useful),
    "Up-Grade": ItemData(BASE_OFFSET+252, ItemClassification.progression),
    "Shell Bell": ItemData(BASE_OFFSET+253, ItemClassification.useful),
    "Sea Incense": ItemData(BASE_OFFSET+254, ItemClassification.progression),
    "Lax Incense": ItemData(BASE_OFFSET+255, ItemClassification.progression),
    "Lucky Punch": ItemData(BASE_OFFSET+256, ItemClassification.useful),
    "Metal Powder": ItemData(BASE_OFFSET+257, ItemClassification.useful),
    "Thick Club": ItemData(BASE_OFFSET+258, ItemClassification.useful),
    "Stick": ItemData(BASE_OFFSET+259, ItemClassification.useful),
    "Wide Lens": ItemData(BASE_OFFSET+265, ItemClassification.useful),
    "Muscle Band": ItemData(BASE_OFFSET+266, ItemClassification.useful),
    "Wise Glasses": ItemData(BASE_OFFSET+267, ItemClassification.useful),
    "Expert Belt": ItemData(BASE_OFFSET+268, ItemClassification.useful),
    "Light Clay": ItemData(BASE_OFFSET+269, ItemClassification.useful),
    "Life Orb": ItemData(BASE_OFFSET+270, ItemClassification.useful),
    "Power Herb": ItemData(BASE_OFFSET+271, ItemClassification.useful),
    "Toxic Orb": ItemData(BASE_OFFSET+272, ItemClassification.useful),
    "Flame Orb": ItemData(BASE_OFFSET+273, ItemClassification.useful),
    "Quick Powder": ItemData(BASE_OFFSET+274, ItemClassification.useful),
    "Focus Sash": ItemData(BASE_OFFSET+275, ItemClassification.useful),
    "Zoom Lens": ItemData(BASE_OFFSET+276, ItemClassification.useful),
    "Metronome": ItemData(BASE_OFFSET+277, ItemClassification.useful),
    "Iron Ball": ItemData(BASE_OFFSET+278, ItemClassification.useful),
    "Lagging Tail": ItemData(BASE_OFFSET+279, ItemClassification.useful),
    "Destiny Knot": ItemData(BASE_OFFSET+280, ItemClassification.useful),
    "Black Sludge": ItemData(BASE_OFFSET+281, ItemClassification.useful),
    "Icy Rock": ItemData(BASE_OFFSET+282, ItemClassification.useful),
    "Smooth Rock": ItemData(BASE_OFFSET+283, ItemClassification.useful),
    "Heat Rock": ItemData(BASE_OFFSET+284, ItemClassification.useful),
    "Damp Rock": ItemData(BASE_OFFSET+285, ItemClassification.useful),
    "Grip Claw": ItemData(BASE_OFFSET+286, ItemClassification.useful),
    "Choice Scarf": ItemData(BASE_OFFSET+287, ItemClassification.useful),
    "Sticky Barb": ItemData(BASE_OFFSET+288, ItemClassification.useful),
    "Power Bracer": ItemData(BASE_OFFSET+289, ItemClassification.useful),
    "Power Belt": ItemData(BASE_OFFSET+290, ItemClassification.useful),
    "Power Lens": ItemData(BASE_OFFSET+291, ItemClassification.useful),
    "Power Band": ItemData(BASE_OFFSET+292, ItemClassification.useful),
    "Power Anklet": ItemData(BASE_OFFSET+293, ItemClassification.useful),
    "Power Weight": ItemData(BASE_OFFSET+294, ItemClassification.useful),
    "Shed Shell": ItemData(BASE_OFFSET+295, ItemClassification.useful),
    "Big Root": ItemData(BASE_OFFSET+296, ItemClassification.useful),
    "Choice Specs": ItemData(BASE_OFFSET+297, ItemClassification.useful),
    "Flame Plate": ItemData(BASE_OFFSET+298, ItemClassification.useful),
    "Splash Plate": ItemData(BASE_OFFSET+299, ItemClassification.useful),
    "Zap Plate": ItemData(BASE_OFFSET+300, ItemClassification.useful),
    "Meadow Plate": ItemData(BASE_OFFSET+301, ItemClassification.useful),
    "Icicle Plate": ItemData(BASE_OFFSET+302, ItemClassification.useful),
    "Fist Plate": ItemData(BASE_OFFSET+303, ItemClassification.useful),
    "Toxic Plate": ItemData(BASE_OFFSET+304, ItemClassification.useful),
    "Earth Plate": ItemData(BASE_OFFSET+305, ItemClassification.useful),
    "Sky Plate": ItemData(BASE_OFFSET+306, ItemClassification.useful),
    "Mind Plate": ItemData(BASE_OFFSET+307, ItemClassification.useful),
    "Insect Plate": ItemData(BASE_OFFSET+308, ItemClassification.useful),
    "Stone Plate": ItemData(BASE_OFFSET+309, ItemClassification.useful),
    "Spooky Plate": ItemData(BASE_OFFSET+310, ItemClassification.useful),
    "Draco Plate": ItemData(BASE_OFFSET+311, ItemClassification.useful),
    "Dread Plate": ItemData(BASE_OFFSET+312, ItemClassification.useful),
    "Iron Plate": ItemData(BASE_OFFSET+313, ItemClassification.useful),
    "Odd Incense": ItemData(BASE_OFFSET+314, ItemClassification.progression),
    "Rock Incense": ItemData(BASE_OFFSET+315, ItemClassification.progression),
    "Full Incense": ItemData(BASE_OFFSET+316, ItemClassification.progression),
    "Wave Incense": ItemData(BASE_OFFSET+317, ItemClassification.progression),
    "Rose Incense": ItemData(BASE_OFFSET+318, ItemClassification.progression),
    "Luck Incense": ItemData(BASE_OFFSET+319, ItemClassification.progression),
    "Pure Incense": ItemData(BASE_OFFSET+320, ItemClassification.progression),
    "Protector": ItemData(BASE_OFFSET+321, ItemClassification.progression),
    "Electirizer": ItemData(BASE_OFFSET+322, ItemClassification.progression),
    "Magmarizer": ItemData(BASE_OFFSET+323, ItemClassification.progression),
    "Dubious Disc": ItemData(BASE_OFFSET+324, ItemClassification.progression),
    "Reaper Cloth": ItemData(BASE_OFFSET+325, ItemClassification.progression),
    "Razor Claw": ItemData(BASE_OFFSET+326, ItemClassification.progression),
    "Razor Fang": ItemData(BASE_OFFSET+327, ItemClassification.progression),
    "TM01": ItemData(BASE_OFFSET+328, ItemClassification.useful),
    "TM02": ItemData(BASE_OFFSET+329, ItemClassification.useful),
    "TM03": ItemData(BASE_OFFSET+330, ItemClassification.useful),
    "TM04": ItemData(BASE_OFFSET+331, ItemClassification.useful),
    "TM05": ItemData(BASE_OFFSET+332, ItemClassification.useful),
    "TM06": ItemData(BASE_OFFSET+333, ItemClassification.useful),
    "TM07": ItemData(BASE_OFFSET+334, ItemClassification.useful),
    "TM08": ItemData(BASE_OFFSET+335, ItemClassification.useful),
    "TM09": ItemData(BASE_OFFSET+336, ItemClassification.useful),
    "TM10": ItemData(BASE_OFFSET+337, ItemClassification.useful),
    "TM11": ItemData(BASE_OFFSET+338, ItemClassification.useful),
    "TM12": ItemData(BASE_OFFSET+339, ItemClassification.useful),
    "TM13": ItemData(BASE_OFFSET+340, ItemClassification.useful),
    "TM14": ItemData(BASE_OFFSET+341, ItemClassification.useful),
    "TM15": ItemData(BASE_OFFSET+342, ItemClassification.useful),
    "TM16": ItemData(BASE_OFFSET+343, ItemClassification.useful),
    "TM17": ItemData(BASE_OFFSET+344, ItemClassification.useful),
    "TM18": ItemData(BASE_OFFSET+345, ItemClassification.useful),
    "TM19": ItemData(BASE_OFFSET+346, ItemClassification.useful),
    "TM20": ItemData(BASE_OFFSET+347, ItemClassification.useful),
    "TM21": ItemData(BASE_OFFSET+348, ItemClassification.useful),
    "TM22": ItemData(BASE_OFFSET+349, ItemClassification.useful),
    "TM23": ItemData(BASE_OFFSET+350, ItemClassification.useful),
    "TM24": ItemData(BASE_OFFSET+351, ItemClassification.useful),
    "TM25": ItemData(BASE_OFFSET+352, ItemClassification.useful),
    "TM26": ItemData(BASE_OFFSET+353, ItemClassification.useful),
    "TM27": ItemData(BASE_OFFSET+354, ItemClassification.useful),
    "TM28": ItemData(BASE_OFFSET+355, ItemClassification.useful),
    "TM29": ItemData(BASE_OFFSET+356, ItemClassification.useful),
    "TM30": ItemData(BASE_OFFSET+357, ItemClassification.useful),
    "TM31": ItemData(BASE_OFFSET+358, ItemClassification.useful),
    "TM32": ItemData(BASE_OFFSET+359, ItemClassification.useful),
    "TM33": ItemData(BASE_OFFSET+360, ItemClassification.useful),
    "TM34": ItemData(BASE_OFFSET+361, ItemClassification.useful),
    "TM35": ItemData(BASE_OFFSET+362, ItemClassification.useful),
    "TM36": ItemData(BASE_OFFSET+363, ItemClassification.useful),
    "TM37": ItemData(BASE_OFFSET+364, ItemClassification.useful),
    "TM38": ItemData(BASE_OFFSET+365, ItemClassification.useful),
    "TM39": ItemData(BASE_OFFSET+366, ItemClassification.useful),
    "TM40": ItemData(BASE_OFFSET+367, ItemClassification.useful),
    "TM41": ItemData(BASE_OFFSET+368, ItemClassification.useful),
    "TM42": ItemData(BASE_OFFSET+369, ItemClassification.useful),
    "TM43": ItemData(BASE_OFFSET+370, ItemClassification.useful),
    "TM44": ItemData(BASE_OFFSET+371, ItemClassification.useful),
    "TM45": ItemData(BASE_OFFSET+372, ItemClassification.useful),
    "TM46": ItemData(BASE_OFFSET+373, ItemClassification.useful),
    "TM47": ItemData(BASE_OFFSET+374, ItemClassification.useful),
    "TM48": ItemData(BASE_OFFSET+375, ItemClassification.useful),
    "TM49": ItemData(BASE_OFFSET+376, ItemClassification.useful),
    "TM50": ItemData(BASE_OFFSET+377, ItemClassification.useful),
    "TM51": ItemData(BASE_OFFSET+378, ItemClassification.useful),
    "TM52": ItemData(BASE_OFFSET+379, ItemClassification.useful),
    "TM53": ItemData(BASE_OFFSET+380, ItemClassification.useful),
    "TM54": ItemData(BASE_OFFSET+381, ItemClassification.useful),
    "TM55": ItemData(BASE_OFFSET+382, ItemClassification.useful),
    "TM56": ItemData(BASE_OFFSET+383, ItemClassification.useful),
    "TM57": ItemData(BASE_OFFSET+384, ItemClassification.useful),
    "TM58": ItemData(BASE_OFFSET+385, ItemClassification.useful),
    "TM59": ItemData(BASE_OFFSET+386, ItemClassification.useful),
    "TM60": ItemData(BASE_OFFSET+387, ItemClassification.useful),
    "TM61": ItemData(BASE_OFFSET+388, ItemClassification.useful),
    "TM62": ItemData(BASE_OFFSET+389, ItemClassification.useful),
    "TM63": ItemData(BASE_OFFSET+390, ItemClassification.useful),
    "TM64": ItemData(BASE_OFFSET+391, ItemClassification.useful),
    "TM65": ItemData(BASE_OFFSET+392, ItemClassification.useful),
    "TM66": ItemData(BASE_OFFSET+393, ItemClassification.useful),
    "TM67": ItemData(BASE_OFFSET+394, ItemClassification.useful),
    "TM68": ItemData(BASE_OFFSET+395, ItemClassification.useful),
    "TM69": ItemData(BASE_OFFSET+396, ItemClassification.useful),
    "TM70": ItemData(BASE_OFFSET+397, ItemClassification.useful),
    "TM71": ItemData(BASE_OFFSET+398, ItemClassification.useful),
    "TM72": ItemData(BASE_OFFSET+399, ItemClassification.useful),
    "TM73": ItemData(BASE_OFFSET+400, ItemClassification.useful),
    "TM74": ItemData(BASE_OFFSET+401, ItemClassification.useful),
    "TM75": ItemData(BASE_OFFSET+402, ItemClassification.useful),
    "TM76": ItemData(BASE_OFFSET+403, ItemClassification.useful),
    "TM77": ItemData(BASE_OFFSET+404, ItemClassification.useful),
    "TM78": ItemData(BASE_OFFSET+405, ItemClassification.useful),
    "TM79": ItemData(BASE_OFFSET+406, ItemClassification.useful),
    "TM80": ItemData(BASE_OFFSET+407, ItemClassification.useful),
    "TM81": ItemData(BASE_OFFSET+408, ItemClassification.useful),
    "TM82": ItemData(BASE_OFFSET+409, ItemClassification.useful),
    "TM83": ItemData(BASE_OFFSET+410, ItemClassification.useful),
    "TM84": ItemData(BASE_OFFSET+411, ItemClassification.useful),
    "TM85": ItemData(BASE_OFFSET+412, ItemClassification.useful),
    "TM86": ItemData(BASE_OFFSET+413, ItemClassification.useful),
    "TM87": ItemData(BASE_OFFSET+414, ItemClassification.useful),
    "TM88": ItemData(BASE_OFFSET+415, ItemClassification.useful),
    "TM89": ItemData(BASE_OFFSET+416, ItemClassification.useful),
    "TM90": ItemData(BASE_OFFSET+417, ItemClassification.useful),
    "TM91": ItemData(BASE_OFFSET+418, ItemClassification.useful),
    "TM92": ItemData(BASE_OFFSET+419, ItemClassification.useful),
    "HM01 Cut": ItemData(BASE_OFFSET+420, ItemClassification.progression),
    "HM02 Fly": ItemData(BASE_OFFSET+421, ItemClassification.progression),
    "HM03 Surf": ItemData(BASE_OFFSET+422, ItemClassification.progression),
    "HM04 Strength": ItemData(BASE_OFFSET+423, ItemClassification.progression),
    "HM05 Waterfall": ItemData(BASE_OFFSET+424, ItemClassification.progression),
    "HM06 Dive": ItemData(BASE_OFFSET+425, ItemClassification.progression),
    #"Reserved 7": ItemData(BASE_OFFSET+426, ItemClassification.filler),
    #"Reserved 8": ItemData(BASE_OFFSET+427, ItemClassification.filler),
    "Town Map": ItemData(BASE_OFFSET+442, ItemClassification.progression),
    "Super Rod": ItemData(BASE_OFFSET+447, ItemClassification.progression),
    "Bicycle": ItemData(BASE_OFFSET+450, ItemClassification.progression),
    "Lunar Wing": ItemData(BASE_OFFSET+453, ItemClassification.progression),
    "Magma Stone": ItemData(BASE_OFFSET+458, ItemClassification.progression),
    "Vs. Recorder": ItemData(BASE_OFFSET+465, ItemClassification.progression),
    "Gracidea": ItemData(BASE_OFFSET+466, ItemClassification.useful),
    "Dowsing MCHN": ItemData(BASE_OFFSET+471, ItemClassification.progression),
    #"Fast Ball": ItemData(BASE_OFFSET+492, ItemClassification.filler),  #TODO: Look into reimplementing
    #"Level Ball": ItemData(BASE_OFFSET+493, ItemClassification.filler),
    #"Lure Ball": ItemData(BASE_OFFSET+494, ItemClassification.filler),
    #"Heavy Ball": ItemData(BASE_OFFSET+495, ItemClassification.filler),
    #"Love Ball": ItemData(BASE_OFFSET+496, ItemClassification.filler),
    #"Friend Ball": ItemData(BASE_OFFSET+497, ItemClassification.filler),
    #"Moon Ball": ItemData(BASE_OFFSET+498, ItemClassification.filler),
    "RageCandyBar": ItemData(BASE_OFFSET+504, ItemClassification.progression),
    #"Enigma Stone": ItemData(BASE_OFFSET+536, ItemClassification.filler),  # maybe lock with this instead of Soul Dew?
    "Prism Scale": ItemData(BASE_OFFSET+537, ItemClassification.progression),
    "Eviolite": ItemData(BASE_OFFSET+538, ItemClassification.useful),
    "Float Stone": ItemData(BASE_OFFSET+539, ItemClassification.useful),
    "Rocky Helmet": ItemData(BASE_OFFSET+540, ItemClassification.useful),
    "Air Balloon": ItemData(BASE_OFFSET+541, ItemClassification.useful),
    "Red Card": ItemData(BASE_OFFSET+542, ItemClassification.useful),
    "Ring Target": ItemData(BASE_OFFSET+543, ItemClassification.useful),
    "Binding Band": ItemData(BASE_OFFSET+544, ItemClassification.useful),
    "Absorb Bulb": ItemData(BASE_OFFSET+545, ItemClassification.useful),
    "Cell Battery": ItemData(BASE_OFFSET+546, ItemClassification.useful),
    "Eject Button": ItemData(BASE_OFFSET+547, ItemClassification.useful),
    "Fire Gem": ItemData(BASE_OFFSET+548, ItemClassification.useful),
    "Water Gem": ItemData(BASE_OFFSET+549, ItemClassification.useful),
    "Electric Gem": ItemData(BASE_OFFSET+550, ItemClassification.useful),
    "Grass Gem": ItemData(BASE_OFFSET+551, ItemClassification.useful),
    "Ice Gem": ItemData(BASE_OFFSET+552, ItemClassification.useful),
    "Fighting Gem": ItemData(BASE_OFFSET+553, ItemClassification.useful),
    "Poison Gem": ItemData(BASE_OFFSET+554, ItemClassification.useful),
    "Ground Gem": ItemData(BASE_OFFSET+555, ItemClassification.useful),
    "Flying Gem": ItemData(BASE_OFFSET+556, ItemClassification.useful),
    "Psychic Gem": ItemData(BASE_OFFSET+557, ItemClassification.useful),
    "Bug Gem": ItemData(BASE_OFFSET+558, ItemClassification.useful),
    "Rock Gem": ItemData(BASE_OFFSET+559, ItemClassification.useful),
    "Ghost Gem": ItemData(BASE_OFFSET+560, ItemClassification.useful),
    "Dragon Gem": ItemData(BASE_OFFSET+561, ItemClassification.useful),
    "Dark Gem": ItemData(BASE_OFFSET+562, ItemClassification.useful),
    "Steel Gem": ItemData(BASE_OFFSET+563, ItemClassification.useful),
    "Normal Gem": ItemData(BASE_OFFSET+564, ItemClassification.useful),
    "Health Wing": ItemData(BASE_OFFSET+565, ItemClassification.filler),
    "Muscle Wing": ItemData(BASE_OFFSET+566, ItemClassification.filler),
    "Resist Wing": ItemData(BASE_OFFSET+567, ItemClassification.filler),
    "Genius Wing": ItemData(BASE_OFFSET+568, ItemClassification.filler),
    "Clever Wing": ItemData(BASE_OFFSET+569, ItemClassification.filler),
    "Swift Wing": ItemData(BASE_OFFSET+570, ItemClassification.filler),
    "Pretty Wing": ItemData(BASE_OFFSET+571, ItemClassification.filler),
    "Cover Fossil": ItemData(BASE_OFFSET+572, ItemClassification.progression),
    "Plume Fossil": ItemData(BASE_OFFSET+573, ItemClassification.progression),
    "Ferry Pass": ItemData(BASE_OFFSET+574, ItemClassification.progression),  # vanilla Liberty Pass
    "Poke Toy": ItemData(BASE_OFFSET+577, ItemClassification.filler),
    "Prop Case": ItemData(BASE_OFFSET+578, ItemClassification.progression),  # would this even lock stuff outside of medal logic?
    "BalmMushroom": ItemData(BASE_OFFSET+580, ItemClassification.filler),
    "Big Nugget": ItemData(BASE_OFFSET+581, ItemClassification.filler),
    "Pearl String": ItemData(BASE_OFFSET+582, ItemClassification.filler),
    "Comet Shard": ItemData(BASE_OFFSET+583, ItemClassification.filler),
    "Relic Copper": ItemData(BASE_OFFSET+584, ItemClassification.filler),
    "Relic Silver": ItemData(BASE_OFFSET+585, ItemClassification.filler),
    "Relic Gold": ItemData(BASE_OFFSET+586, ItemClassification.filler),
    "Relic Vase": ItemData(BASE_OFFSET+587, ItemClassification.filler),
    "Relic Band": ItemData(BASE_OFFSET+588, ItemClassification.filler),
    "Relic Statue": ItemData(BASE_OFFSET+589, ItemClassification.filler),
    "Relic Crown": ItemData(BASE_OFFSET+590, ItemClassification.filler),
    "Casteliacone": ItemData(BASE_OFFSET+591, ItemClassification.filler),
    "Light Stone": ItemData(BASE_OFFSET+616, ItemClassification.progression),  # do these work on the other version? good question
    "Dark Stone": ItemData(BASE_OFFSET+617, ItemClassification.progression),  # they do now
    "TM93": ItemData(BASE_OFFSET+618, ItemClassification.useful),
    "TM94": ItemData(BASE_OFFSET+619, ItemClassification.useful),
    "TM95": ItemData(BASE_OFFSET+620, ItemClassification.useful),
    "Season Machine": ItemData(BASE_OFFSET+622, ItemClassification.progression),  # God Stone
    "Hugh's Town Map": ItemData(BASE_OFFSET+622, ItemClassification.progression),  # Gram 1
    "Medal Box": ItemData(BASE_OFFSET+627, ItemClassification.progression),
    "DNA Splicers": ItemData(BASE_OFFSET+628, ItemClassification.progression),
    "Permit": ItemData(BASE_OFFSET+630, ItemClassification.progression),
    "Plasma Card": ItemData(BASE_OFFSET+633, ItemClassification.progression),
    "Grubby Hanky": ItemData(BASE_OFFSET+634, ItemClassification.progression),
    "Colress MCHN": ItemData(BASE_OFFSET+635, ItemClassification.progression),
    "Dropped Item (Yancy)": ItemData(BASE_OFFSET+636, ItemClassification.progression),  # does which one you pick up determine who
    "Dropped Item (Curtis)": ItemData(BASE_OFFSET+637, ItemClassification.progression),  # calls?
    "Reveal Glass": ItemData(BASE_OFFSET+638, ItemClassification.useful),
}

item_groups = {
    "Badges": {"Basic Badge", "Toxic Badge", "Insect Badge", "Bolt Badge",
               "Quake Badge", "Jet Badge", "Legend Badge", "Wave Badge"},
    "HMs": {"HM01 Cut", "HM02 Fly", "HM03 Surf", "HM04 Strength", "HM05 Waterfall", "HM06 Dive"},
    "HM01": {"HM01 Cut"},
    "HM02": {"HM02 Fly"},
    "HM03": {"HM03 Surf"},
    "HM04": {"HM04 Strength"},
    "HM05": {"HM05 Waterfall"},
    "HM06": {"HM06 Dive"},
}

filler_items = {item: all_items[item].code for item in all_items if all_items[item].classification == ItemClassification.filler}
key_items = {item: all_items[item].code for item in ["Reveal Glass", "Dropped Item (Yancy)", "Colress MCHN",
                                                     "Grubby Hanky", "Plasma Card", "Permit", "DNA Splicers",
                                                     "Medal Box", "Season Machine", "Light Stone", "Town Map",
                                                     "Hugh's Town Map", "Bicycle", "Dowsing MCHN", "HM01 Cut",
                                                     "HM02 Fly", "HM03 Surf", "HM04 Strength", "HM05 Waterfall",
                                                     "HM06 Dive", "Basic Badge", "Toxic Badge", "Insect Badge",
                                                     "Bolt Badge", "Quake Badge", "Jet Badge", "Legend Badge",
                                                     "Wave Badge", "Lunar Wing", "Magma Stone", "Gracidea",
                                                     "Permit", "Super Rod", "Vs. Recorder"]}


def generate_itempool(world: "PokemonBW2World"):
    default_tags = ["EVENT"]
    if not world.options.key_items:
        default_tags.append("KEY")
    if not world.options.hms:
        default_tags.append("HM")
    if world.options.badges == 0:
        default_tags.append("BADGE")
    itempool = []
    for location in world.multiworld.regions.location_cache[world.player]:
        # is this a cursed method of attack for my items, probably!
        location_info = location_data[location]
        if any(tag in location_info["tags"] for tag in default_tags):
            # grab and create the default item, and place it
            world.multiworld.get_location(location, world.player)\
                .place_locked_item(world.create_item(location_info["default"],
                                                     True if "EVENT" in location_info["tags"] else False))
        # else, add the item to the item pool
        elif location_info["default"] in filler_items:
            # generate a random filler instead
            itempool.append(world.create_item(world.get_filler_item_name()))
        else:
            itempool.append(world.create_item(location_info["default"]))

    world.multiworld.itempool += itempool
