import typing
from BaseClasses import Item, ItemClassification


class ItemData(typing.NamedTuple):
    code: typing.Optional[int]
    classification: ItemClassification
    quantity: int = 1
    skip_balancing: bool = False
    trap: bool = False


class PokemonBW2Item(Item):
    game = "Pokemon Black 2 and White 2"


all_items = {
    "Master Ball": ItemData(1, ItemClassification.filler),
    "Ultra Ball": ItemData(2, ItemClassification.filler, 5),
    "Great Ball": ItemData(3, ItemClassification.filler, 5),
    "Poké Ball": ItemData(4, ItemClassification.filler, 5),
    "Safari Ball": ItemData(5, ItemClassification.filler, 5),
    "Net Ball": ItemData(6, ItemClassification.filler, 5),
    "Dive Ball": ItemData(7, ItemClassification.filler, 5),
    "Nest Ball": ItemData(8, ItemClassification.filler, 5),
    "Repeat Ball": ItemData(9, ItemClassification.filler, 5),
    "Timer Ball": ItemData(10, ItemClassification.filler, 5),
    "Luxury Ball": ItemData(11, ItemClassification.filler, 5),
    "Premier Ball": ItemData(12, ItemClassification.filler, 5),
    "Dusk Ball": ItemData(13, ItemClassification.filler, 5),
    "Heal Ball": ItemData(14, ItemClassification.filler, 5),
    "Quick Ball": ItemData(15, ItemClassification.filler, 5),
    "Potion": ItemData(17, ItemClassification.filler),
    "Antidote": ItemData(18, ItemClassification.filler),
    "Burn Heal": ItemData(19, ItemClassification.filler),
    "Ice Heal": ItemData(20, ItemClassification.filler),
    "Awakening": ItemData(21, ItemClassification.filler),
    "Parlyz Heal": ItemData(22, ItemClassification.filler),
    "Full Restore": ItemData(23, ItemClassification.filler),
    "Max Potion": ItemData(24, ItemClassification.filler),
    "Hyper Potion": ItemData(25, ItemClassification.filler),
    "Super Potion": ItemData(26, ItemClassification.filler),
    "Full Heal": ItemData(27, ItemClassification.filler),
    "Revive": ItemData(28, ItemClassification.filler),
    "Max Revive": ItemData(29, ItemClassification.filler),
    "Fresh Water": ItemData(30, ItemClassification.filler),
    "Soda Pop": ItemData(31, ItemClassification.filler),
    "Lemonade": ItemData(32, ItemClassification.filler),
    "Moomoo Milk": ItemData(33, ItemClassification.filler),
    "EnergyPowder": ItemData(34, ItemClassification.filler),
    "Energy Root": ItemData(35, ItemClassification.filler),
    "Heal Powder": ItemData(36, ItemClassification.filler),
    "Revival Herb": ItemData(37, ItemClassification.filler),
    "Ether": ItemData(38, ItemClassification.filler),
    "Max Ether": ItemData(39, ItemClassification.filler),
    "Elixir": ItemData(40, ItemClassification.filler),
    "Max Elixir": ItemData(41, ItemClassification.filler),
    "Lava Cookie": ItemData(42, ItemClassification.filler),
    "Berry Juice": ItemData(43, ItemClassification.filler),
    "Sacred Ash": ItemData(44, ItemClassification.filler),
    "HP Up": ItemData(45, ItemClassification.filler),
    "Protein": ItemData(46, ItemClassification.filler),
    "Iron": ItemData(47, ItemClassification.filler),
    "Carbos": ItemData(48, ItemClassification.filler),
    "Calcium": ItemData(49, ItemClassification.filler),
    "Rare Candy": ItemData(50, ItemClassification.filler),
    "PP Up": ItemData(51, ItemClassification.filler),
    "Zinc": ItemData(52, ItemClassification.filler),
    "PP Max": ItemData(53, ItemClassification.filler),
    "Old Gateau": ItemData(54, ItemClassification.filler),
    "Guard Spec.": ItemData(55, ItemClassification.filler),
    "Dire Hit": ItemData(56, ItemClassification.filler),
    "X Attack": ItemData(57, ItemClassification.filler),
    "X Defend": ItemData(58, ItemClassification.filler),
    "X Speed": ItemData(59, ItemClassification.filler),
    "X Accuracy": ItemData(60, ItemClassification.filler),
    "X Special": ItemData(61, ItemClassification.filler),
    "X Sp. Def": ItemData(62, ItemClassification.filler),
    "Poké Doll": ItemData(63, ItemClassification.filler),
    "Fluffy Tail": ItemData(64, ItemClassification.filler),
    "Blue Flute": ItemData(65, ItemClassification.filler),
    "Yellow Flute": ItemData(66, ItemClassification.filler),
    "Red Flute": ItemData(67, ItemClassification.filler),
    "Black Flute": ItemData(68, ItemClassification.filler),
    "White Flute": ItemData(69, ItemClassification.filler),
    "Shoal Salt": ItemData(70, ItemClassification.filler),
    "Shoal Shell": ItemData(71, ItemClassification.filler),
    "Red Shard": ItemData(72, ItemClassification.filler),
    "Blue Shard": ItemData(73, ItemClassification.filler),
    "Yellow Shard": ItemData(74, ItemClassification.filler),
    "Green Shard": ItemData(75, ItemClassification.filler),
    "Super Repel": ItemData(76, ItemClassification.filler),
    "Max Repel": ItemData(77, ItemClassification.filler),
    "Escape Rope": ItemData(78, ItemClassification.filler),
    "Repel": ItemData(79, ItemClassification.filler),
    "Sun Stone": ItemData(80, ItemClassification.filler),
    "Moon Stone": ItemData(81, ItemClassification.filler),
    "Fire Stone": ItemData(82, ItemClassification.filler),
    "Thunderstone": ItemData(83, ItemClassification.filler),
    "Water Stone": ItemData(84, ItemClassification.filler),
    "Leaf Stone": ItemData(85, ItemClassification.filler),
    "TinyMushroom": ItemData(86, ItemClassification.filler),
    "Big Mushroom": ItemData(87, ItemClassification.filler),
    "Pearl": ItemData(88, ItemClassification.filler),
    "Big Pearl": ItemData(89, ItemClassification.filler),
    "Stardust": ItemData(90, ItemClassification.filler),
    "Star Piece": ItemData(91, ItemClassification.filler),
    "Nugget": ItemData(92, ItemClassification.filler),
    "Heart Scale": ItemData(93, ItemClassification.filler),
    "Honey": ItemData(94, ItemClassification.filler),
    "Growth Mulch": ItemData(95, ItemClassification.filler),
    "Damp Mulch": ItemData(96, ItemClassification.filler),
    "Stable Mulch": ItemData(97, ItemClassification.filler),
    "Gooey Mulch": ItemData(98, ItemClassification.filler),
    "Root Fossil": ItemData(99, ItemClassification.progression),
    "Claw Fossil": ItemData(100, ItemClassification.progression),
    "Helix Fossil": ItemData(101, ItemClassification.progression),
    "Dome Fossil": ItemData(102, ItemClassification.progression),
    "Old Amber": ItemData(103, ItemClassification.progression),
    "Armor Fossil": ItemData(104, ItemClassification.progression),
    "Skull Fossil": ItemData(105, ItemClassification.progression),
    "Rare Bone": ItemData(106, ItemClassification.filler),
    "Shiny Stone": ItemData(107, ItemClassification.progression),
    "Dusk Stone": ItemData(108, ItemClassification.progression),
    "Dawn Stone": ItemData(109, ItemClassification.progression),
    "Oval Stone": ItemData(110, ItemClassification.progression),
    "Griseous Orb": ItemData(112, ItemClassification.filler),
    # Reserve 113 for Archipelago Item
    "Douse Drive": ItemData(116, ItemClassification.filler),
    "Shock Drive": ItemData(117, ItemClassification.filler),
    "Burn Drive": ItemData(118, ItemClassification.filler),
    "Chill Drive": ItemData(119, ItemClassification.filler),
    "Basic Badge": ItemData(120, ItemClassification.progression),
    "Toxic Badge": ItemData(121, ItemClassification.progression),
    "Insect Badge": ItemData(122, ItemClassification.progression),
    "Bolt Badge": ItemData(123, ItemClassification.progression),
    "Quake Badge": ItemData(124, ItemClassification.progression),
    "Jet Badge": ItemData(125, ItemClassification.progression),
    "Legend Badge": ItemData(126, ItemClassification.progression),
    "Wave Badge": ItemData(127, ItemClassification.progression),
    "Reserved 1": ItemData(128, ItemClassification.progression),
    "Reserved 2": ItemData(129, ItemClassification.progression),
    "Reserved 3": ItemData(130, ItemClassification.trap),
    "Reserved 4": ItemData(131, ItemClassification.trap),
    "Reserved 5": ItemData(132, ItemClassification.trap),
    "Reserved 6": ItemData(133, ItemClassification.trap),
    "Sweet Heart": ItemData(134, ItemClassification.filler),
    "Adamant Orb": ItemData(135, ItemClassification.useful),
    "Lustrous Orb": ItemData(136, ItemClassification.useful),
    "Cheri Berry": ItemData(149, ItemClassification.filler, 5),
    "Chesto Berry": ItemData(150, ItemClassification.filler, 5),
    "Pecha Berry": ItemData(151, ItemClassification.filler, 5),
    "Rawst Berry": ItemData(152, ItemClassification.filler, 5),
    "Aspear Berry": ItemData(153, ItemClassification.filler, 5),
    "Leppa Berry": ItemData(154, ItemClassification.filler, 5),
    "Oran Berry": ItemData(155, ItemClassification.filler, 5),
    "Persim Berry": ItemData(156, ItemClassification.filler, 5),
    "Lum Berry": ItemData(157, ItemClassification.filler, 5),
    "Sitrus Berry": ItemData(158, ItemClassification.filler, 5),
    "Figy Berry": ItemData(159, ItemClassification.filler, 5),
    "Wiki Berry": ItemData(160, ItemClassification.filler, 5),
    "Mago Berry": ItemData(161, ItemClassification.filler, 5),
    "Aguav Berry": ItemData(162, ItemClassification.filler, 5),
    "Iapapa Berry": ItemData(163, ItemClassification.filler, 5),
    "Razz Berry": ItemData(164, ItemClassification.filler, 5),
    "Bluk Berry": ItemData(165, ItemClassification.filler, 5),
    "Nanab Berry": ItemData(166, ItemClassification.filler, 5),
    "Wepear Berry": ItemData(167, ItemClassification.filler, 5),
    "Pinap Berry": ItemData(168, ItemClassification.filler, 5),
    "Pomeg Berry": ItemData(169, ItemClassification.filler, 5),
    "Kelpsy Berry": ItemData(170, ItemClassification.filler, 5),
    "Qualot Berry": ItemData(171, ItemClassification.filler, 5),
    "Hondew Berry": ItemData(172, ItemClassification.filler, 5),
    "Grepa Berry": ItemData(173, ItemClassification.filler, 5),
    "Tamato Berry": ItemData(174, ItemClassification.filler, 5),
    "Cornn Berry": ItemData(175, ItemClassification.filler, 5),
    "Magost Berry": ItemData(176, ItemClassification.filler, 5),
    "Rabuta Berry": ItemData(177, ItemClassification.filler, 5),
    "Nomel Berry": ItemData(178, ItemClassification.filler, 5),
    "Spelon Berry": ItemData(179, ItemClassification.filler, 5),
    "Pamtre Berry": ItemData(180, ItemClassification.filler, 5),
    "Watmel Berry": ItemData(181, ItemClassification.filler, 5),
    "Durin Berry": ItemData(182, ItemClassification.filler, 5),
    "Belue Berry": ItemData(183, ItemClassification.filler, 5),
    "Occa Berry": ItemData(184, ItemClassification.filler, 5),
    "Passho Berry": ItemData(185, ItemClassification.filler, 5),
    "Wacan Berry": ItemData(186, ItemClassification.filler, 5),
    "Rindo Berry": ItemData(187, ItemClassification.filler, 5),
    "Yache Berry": ItemData(188, ItemClassification.filler, 5),
    "Chople Berry": ItemData(189, ItemClassification.filler, 5),
    "Kebia Berry": ItemData(190, ItemClassification.filler, 5),
    "Shuca Berry": ItemData(191, ItemClassification.filler, 5),
    "Coba Berry": ItemData(192, ItemClassification.filler, 5),
    "Payapa Berry": ItemData(193, ItemClassification.filler, 5),
    "Tanga Berry": ItemData(194, ItemClassification.filler, 5),
    "Charti Berry": ItemData(195, ItemClassification.filler, 5),
    "Kasib Berry": ItemData(196, ItemClassification.filler, 5),
    "Haban Berry": ItemData(197, ItemClassification.filler, 5),
    "Colbur Berry": ItemData(198, ItemClassification.filler, 5),
    "Babiri Berry": ItemData(199, ItemClassification.filler, 5),
    "Chilan Berry": ItemData(200, ItemClassification.filler, 5),
    "Liechi Berry": ItemData(201, ItemClassification.filler, 5),
    "Ganlon Berry": ItemData(202, ItemClassification.filler, 5),
    "Salac Berry": ItemData(203, ItemClassification.filler, 5),
    "Petaya Berry": ItemData(204, ItemClassification.filler, 5),
    "Apicot Berry": ItemData(205, ItemClassification.filler, 5),
    "Lansat Berry": ItemData(206, ItemClassification.filler, 5),
    "Starf Berry": ItemData(207, ItemClassification.filler, 5),
    "Enigma Berry": ItemData(208, ItemClassification.filler, 5),
    "Micle Berry": ItemData(209, ItemClassification.filler, 5),
    "Custap Berry": ItemData(210, ItemClassification.filler, 5),
    "Jaboca Berry": ItemData(211, ItemClassification.filler, 5),
    "Rowap Berry": ItemData(212, ItemClassification.filler, 5),
    "BrightPowder": ItemData(213, ItemClassification.useful),
    "White Herb": ItemData(214, ItemClassification.useful),
    "Macho Brace": ItemData(215, ItemClassification.useful),
    "Exp. Share": ItemData(216, ItemClassification.progression),
    "Quick Claw": ItemData(217, ItemClassification.useful),
    "Soothe Bell": ItemData(218, ItemClassification.useful),
    "Mental Herb": ItemData(219, ItemClassification.useful),
    "Choice Band": ItemData(220, ItemClassification.useful),
    "King's Rock": ItemData(221, ItemClassification.progression),
    "SilverPowder": ItemData(222, ItemClassification.useful),
    "Amulet Coin": ItemData(223, ItemClassification.useful),
    "Cleanse Tag": ItemData(224, ItemClassification.useful),
    "Soul Dew": ItemData(225, ItemClassification.useful),  # may change, depends if I wanna lock the Lati encounter here
    "DeepSeaTooth": ItemData(226, ItemClassification.progression),
    "DeepSeaScale": ItemData(227, ItemClassification.progression),
    "Smoke Ball": ItemData(228, ItemClassification.useful),
    "Everstone": ItemData(229, ItemClassification.useful),
    "Focus Band": ItemData(230, ItemClassification.useful),
    "Lucky Egg": ItemData(231, ItemClassification.useful),
    "Scope Lens": ItemData(232, ItemClassification.useful),
    "Metal Coat": ItemData(233, ItemClassification.progression),
    "Leftovers": ItemData(234, ItemClassification.useful),
    "Dragon Scale": ItemData(235, ItemClassification.progression),
    "Light Ball": ItemData(236, ItemClassification.useful),
    "Soft Sand": ItemData(237, ItemClassification.useful),
    "Hard Stone": ItemData(238, ItemClassification.useful),
    "Miracle Seed": ItemData(239, ItemClassification.useful),
    "BlackGlasses": ItemData(240, ItemClassification.useful),
    "Black Belt": ItemData(241, ItemClassification.useful),
    "Magnet": ItemData(242, ItemClassification.useful),
    "Mystic Water": ItemData(243, ItemClassification.useful),
    "Sharp Beak": ItemData(244, ItemClassification.useful),
    "Poison Barb": ItemData(245, ItemClassification.useful),
    "NeverMeltIce": ItemData(246, ItemClassification.useful),
    "Spell Tag": ItemData(247, ItemClassification.useful),
    "TwistedSpoon": ItemData(248, ItemClassification.useful),
    "Charcoal": ItemData(249, ItemClassification.useful),
    "Dragon Fang": ItemData(250, ItemClassification.useful),
    "Silk Scarf": ItemData(251, ItemClassification.useful),
    "Up-Grade": ItemData(252, ItemClassification.progression),
    "Shell Bell": ItemData(253, ItemClassification.useful),
    "Sea Incense": ItemData(254, ItemClassification.progression),
    "Lax Incense": ItemData(255, ItemClassification.progression),
    "Lucky Punch": ItemData(256, ItemClassification.useful),
    "Metal Powder": ItemData(257, ItemClassification.useful),
    "Thick Club": ItemData(258, ItemClassification.useful),
    "Stick": ItemData(259, ItemClassification.useful),
    "Wide Lens": ItemData(265, ItemClassification.useful),
    "Muscle Band": ItemData(266, ItemClassification.useful),
    "Wise Glasses": ItemData(267, ItemClassification.useful),
    "Expert Belt": ItemData(268, ItemClassification.useful),
    "Light Clay": ItemData(269, ItemClassification.useful),
    "Life Orb": ItemData(270, ItemClassification.useful),
    "Power Herb": ItemData(271, ItemClassification.useful),
    "Toxic Orb": ItemData(272, ItemClassification.useful),
    "Flame Orb": ItemData(273, ItemClassification.useful),
    "Quick Powder": ItemData(274, ItemClassification.useful),
    "Focus Sash": ItemData(275, ItemClassification.useful),
    "Zoom Lens": ItemData(276, ItemClassification.useful),
    "Metronome": ItemData(277, ItemClassification.useful),
    "Iron Ball": ItemData(278, ItemClassification.useful),
    "Lagging Tail": ItemData(279, ItemClassification.useful),
    "Destiny Knot": ItemData(280, ItemClassification.useful),
    "Black Sludge": ItemData(281, ItemClassification.useful),
    "Icy Rock": ItemData(282, ItemClassification.useful),
    "Smooth Rock": ItemData(283, ItemClassification.useful),
    "Heat Rock": ItemData(284, ItemClassification.useful),
    "Damp Rock": ItemData(285, ItemClassification.useful),
    "Grip Claw": ItemData(286, ItemClassification.useful),
    "Choice Scarf": ItemData(287, ItemClassification.useful),
    "Sticky Barb": ItemData(288, ItemClassification.useful),
    "Power Bracer": ItemData(289, ItemClassification.useful),
    "Power Belt": ItemData(290, ItemClassification.useful),
    "Power Lens": ItemData(291, ItemClassification.useful),
    "Power Band": ItemData(292, ItemClassification.useful),
    "Power Anklet": ItemData(293, ItemClassification.useful),
    "Power Weight": ItemData(294, ItemClassification.useful),
    "Shed Shell": ItemData(295, ItemClassification.useful),
    "Big Root": ItemData(296, ItemClassification.useful),
    "Choice Specs": ItemData(297, ItemClassification.useful),
    "Flame Plate": ItemData(298, ItemClassification.useful),
    "Splash Plate": ItemData(299, ItemClassification.useful),
    "Zap Plate": ItemData(300, ItemClassification.useful),
    "Meadow Plate": ItemData(301, ItemClassification.useful),
    "Icicle Plate": ItemData(302, ItemClassification.useful),
    "Fist Plate": ItemData(303, ItemClassification.useful),
    "Toxic Plate": ItemData(304, ItemClassification.useful),
    "Earth Plate": ItemData(305, ItemClassification.useful),
    "Sky Plate": ItemData(306, ItemClassification.useful),
    "Mind Plate": ItemData(307, ItemClassification.useful),
    "Insect Plate": ItemData(308, ItemClassification.useful),
    "Stone Plate": ItemData(309, ItemClassification.useful),
    "Spooky Plate": ItemData(310, ItemClassification.useful),
    "Draco Plate": ItemData(311, ItemClassification.useful),
    "Dread Plate": ItemData(312, ItemClassification.useful),
    "Iron Plate": ItemData(313, ItemClassification.useful),
    "Odd Incense": ItemData(314, ItemClassification.progression),
    "Rock Incense": ItemData(315, ItemClassification.progression),
    "Full Incense": ItemData(316, ItemClassification.progression),
    "Wave Incense": ItemData(317, ItemClassification.progression),
    "Rose Incense": ItemData(318, ItemClassification.progression),
    "Luck Incense": ItemData(319, ItemClassification.progression),
    "Pure Incense": ItemData(320, ItemClassification.progression),
    "Protector": ItemData(321, ItemClassification.progression),
    "Electirizer": ItemData(322, ItemClassification.progression),
    "Magmarizer": ItemData(323, ItemClassification.progression),
    "Dubious Disc": ItemData(324, ItemClassification.progression),
    "Reaper Cloth": ItemData(325, ItemClassification.progression),
    "Razor Claw": ItemData(326, ItemClassification.progression),
    "Razor Fang": ItemData(327, ItemClassification.progression),
    "TM01": ItemData(328, ItemClassification.useful),
    "TM02": ItemData(329, ItemClassification.useful),
    "TM03": ItemData(330, ItemClassification.useful),
    "TM04": ItemData(331, ItemClassification.useful),
    "TM05": ItemData(332, ItemClassification.useful),
    "TM06": ItemData(333, ItemClassification.useful),
    "TM07": ItemData(334, ItemClassification.useful),
    "TM08": ItemData(335, ItemClassification.useful),
    "TM09": ItemData(336, ItemClassification.useful),
    "TM10": ItemData(337, ItemClassification.useful),
    "TM11": ItemData(338, ItemClassification.useful),
    "TM12": ItemData(339, ItemClassification.useful),
    "TM13": ItemData(340, ItemClassification.useful),
    "TM14": ItemData(341, ItemClassification.useful),
    "TM15": ItemData(342, ItemClassification.useful),
    "TM16": ItemData(343, ItemClassification.useful),
    "TM17": ItemData(344, ItemClassification.useful),
    "TM18": ItemData(345, ItemClassification.useful),
    "TM19": ItemData(346, ItemClassification.useful),
    "TM20": ItemData(347, ItemClassification.useful),
    "TM21": ItemData(348, ItemClassification.useful),
    "TM22": ItemData(349, ItemClassification.useful),
    "TM23": ItemData(350, ItemClassification.useful),
    "TM24": ItemData(351, ItemClassification.useful),
    "TM25": ItemData(352, ItemClassification.useful),
    "TM26": ItemData(353, ItemClassification.useful),
    "TM27": ItemData(354, ItemClassification.useful),
    "TM28": ItemData(355, ItemClassification.useful),
    "TM29": ItemData(356, ItemClassification.useful),
    "TM30": ItemData(357, ItemClassification.useful),
    "TM31": ItemData(358, ItemClassification.useful),
    "TM32": ItemData(359, ItemClassification.useful),
    "TM33": ItemData(360, ItemClassification.useful),
    "TM34": ItemData(361, ItemClassification.useful),
    "TM35": ItemData(362, ItemClassification.useful),
    "TM36": ItemData(363, ItemClassification.useful),
    "TM37": ItemData(364, ItemClassification.useful),
    "TM38": ItemData(365, ItemClassification.useful),
    "TM39": ItemData(366, ItemClassification.useful),
    "TM40": ItemData(367, ItemClassification.useful),
    "TM41": ItemData(368, ItemClassification.useful),
    "TM42": ItemData(369, ItemClassification.useful),
    "TM43": ItemData(370, ItemClassification.useful),
    "TM44": ItemData(371, ItemClassification.useful),
    "TM45": ItemData(372, ItemClassification.useful),
    "TM46": ItemData(373, ItemClassification.useful),
    "TM47": ItemData(374, ItemClassification.useful),
    "TM48": ItemData(375, ItemClassification.useful),
    "TM49": ItemData(376, ItemClassification.useful),
    "TM50": ItemData(377, ItemClassification.useful),
    "TM51": ItemData(378, ItemClassification.useful),
    "TM52": ItemData(379, ItemClassification.useful),
    "TM53": ItemData(380, ItemClassification.useful),
    "TM54": ItemData(381, ItemClassification.useful),
    "TM55": ItemData(382, ItemClassification.useful),
    "TM56": ItemData(383, ItemClassification.useful),
    "TM57": ItemData(384, ItemClassification.useful),
    "TM58": ItemData(385, ItemClassification.useful),
    "TM59": ItemData(386, ItemClassification.useful),
    "TM60": ItemData(387, ItemClassification.useful),
    "TM61": ItemData(388, ItemClassification.useful),
    "TM62": ItemData(389, ItemClassification.useful),
    "TM63": ItemData(390, ItemClassification.useful),
    "TM64": ItemData(391, ItemClassification.useful),
    "TM65": ItemData(392, ItemClassification.useful),
    "TM66": ItemData(393, ItemClassification.useful),
    "TM67": ItemData(394, ItemClassification.useful),
    "TM68": ItemData(395, ItemClassification.useful),
    "TM69": ItemData(396, ItemClassification.useful),
    "TM70": ItemData(397, ItemClassification.useful),
    "TM71": ItemData(398, ItemClassification.useful),
    "TM72": ItemData(399, ItemClassification.useful),
    "TM73": ItemData(400, ItemClassification.useful),
    "TM74": ItemData(401, ItemClassification.useful),
    "TM75": ItemData(402, ItemClassification.useful),
    "TM76": ItemData(403, ItemClassification.useful),
    "TM77": ItemData(404, ItemClassification.useful),
    "TM78": ItemData(405, ItemClassification.useful),
    "TM79": ItemData(406, ItemClassification.useful),
    "TM80": ItemData(407, ItemClassification.useful),
    "TM81": ItemData(408, ItemClassification.useful),
    "TM82": ItemData(409, ItemClassification.useful),
    "TM83": ItemData(410, ItemClassification.useful),
    "TM84": ItemData(411, ItemClassification.useful),
    "TM85": ItemData(412, ItemClassification.useful),
    "TM86": ItemData(413, ItemClassification.useful),
    "TM87": ItemData(414, ItemClassification.useful),
    "TM88": ItemData(415, ItemClassification.useful),
    "TM89": ItemData(416, ItemClassification.useful),
    "TM90": ItemData(417, ItemClassification.useful),
    "TM91": ItemData(418, ItemClassification.useful),
    "TM92": ItemData(419, ItemClassification.useful),
    "HM01 Cut": ItemData(420, ItemClassification.progression),
    "HM02 Fly": ItemData(421, ItemClassification.progression),
    "HM03 Surf": ItemData(422, ItemClassification.progression),
    "HM04 Strength": ItemData(423, ItemClassification.progression),
    "HM05 Waterfall": ItemData(424, ItemClassification.progression),
    "HM06 Dive": ItemData(425, ItemClassification.progression),
    "Reserved 7": ItemData(426, ItemClassification.filler),
    "Reserved 8": ItemData(427, ItemClassification.filler),
    "Town Map": ItemData(442, ItemClassification.progression),
    "Bicycle": ItemData(450, ItemClassification.filler),
    "Lunar Wing": ItemData(453, ItemClassification.filler),
    "Magma Stone": ItemData(458, ItemClassification.filler),
    "Gracidea": ItemData(466, ItemClassification.filler),
    "Dowsing MCHN": ItemData(471, ItemClassification.filler),
    #"Fast Ball": ItemData(492, ItemClassification.filler),  #TODO: Look into reimplementing
    #"Level Ball": ItemData(493, ItemClassification.filler),
    #"Lure Ball": ItemData(494, ItemClassification.filler),
    #"Heavy Ball": ItemData(495, ItemClassification.filler),
    #"Love Ball": ItemData(496, ItemClassification.filler),
    #"Friend Ball": ItemData(497, ItemClassification.filler),
    #"Moon Ball": ItemData(498, ItemClassification.filler),
    "RageCandyBar": ItemData(504, ItemClassification.progression),
    #"Enigma Stone": ItemData(536, ItemClassification.filler),  # maybe lock with this instead of Soul Dew?
    "Prism Scale": ItemData(537, ItemClassification.progression),
    "Eviolite": ItemData(538, ItemClassification.useful),
    "Float Stone": ItemData(539, ItemClassification.useful),
    "Rocky Helmet": ItemData(540, ItemClassification.useful),
    "Air Balloon": ItemData(541, ItemClassification.useful),
    "Red Card": ItemData(542, ItemClassification.useful),
    "Ring Target": ItemData(543, ItemClassification.useful),
    "Binding Band": ItemData(544, ItemClassification.useful),
    "Absorb Bulb": ItemData(545, ItemClassification.useful),
    "Cell Battery": ItemData(546, ItemClassification.useful),
    "Eject Button": ItemData(547, ItemClassification.useful),
    "Fire Gem": ItemData(548, ItemClassification.useful),
    "Water Gem": ItemData(549, ItemClassification.useful),
    "Electric Gem": ItemData(550, ItemClassification.useful),
    "Grass Gem": ItemData(551, ItemClassification.useful),
    "Ice Gem": ItemData(552, ItemClassification.useful),
    "Fighting Gem": ItemData(553, ItemClassification.useful),
    "Poison Gem": ItemData(554, ItemClassification.useful),
    "Ground Gem": ItemData(555, ItemClassification.useful),
    "Flying Gem": ItemData(556, ItemClassification.useful),
    "Psychic Gem": ItemData(557, ItemClassification.useful),
    "Bug Gem": ItemData(558, ItemClassification.useful),
    "Rock Gem": ItemData(559, ItemClassification.useful),
    "Ghost Gem": ItemData(560, ItemClassification.useful),
    "Dragon Gem": ItemData(561, ItemClassification.useful),
    "Dark Gem": ItemData(562, ItemClassification.useful),
    "Steel Gem": ItemData(563, ItemClassification.useful),
    "Normal Gem": ItemData(564, ItemClassification.useful),
    "Health Wing": ItemData(565, ItemClassification.filler),
    "Muscle Wing": ItemData(566, ItemClassification.filler),
    "Resist Wing": ItemData(567, ItemClassification.filler),
    "Genius Wing": ItemData(568, ItemClassification.filler),
    "Clever Wing": ItemData(569, ItemClassification.filler),
    "Swift Wing": ItemData(570, ItemClassification.filler),
    "Pretty Wing": ItemData(571, ItemClassification.filler),
    "Cover Fossil": ItemData(572, ItemClassification.progression),
    "Plume Fossil": ItemData(573, ItemClassification.progression),
    "Poké Toy": ItemData(577, ItemClassification.filler),
    "Prop Case": ItemData(578, ItemClassification.progression),  # would this even lock stuff outside of medal logic?
    "BalmMushroom": ItemData(580, ItemClassification.filler),
    "Big Nugget": ItemData(581, ItemClassification.filler),
    "Pearl String": ItemData(582, ItemClassification.filler),
    "Comet Shard": ItemData(583, ItemClassification.filler),
    "Relic Copper": ItemData(584, ItemClassification.filler),
    "Relic Silver": ItemData(585, ItemClassification.filler),
    "Relic Gold": ItemData(586, ItemClassification.filler),
    "Relic Vase": ItemData(587, ItemClassification.filler),
    "Relic Band": ItemData(588, ItemClassification.filler),
    "Relic Statue": ItemData(589, ItemClassification.filler),
    "Relic Crown": ItemData(590, ItemClassification.filler),
    "Casteliacone": ItemData(591, ItemClassification.filler),
    "Light Stone": ItemData(616, ItemClassification.progression),  # do these work on the other version? good question
    "Dark Stone": ItemData(617, ItemClassification.progression),  # they do now
    "TM93": ItemData(618, ItemClassification.useful),
    "TM94": ItemData(619, ItemClassification.useful),
    "TM95": ItemData(620, ItemClassification.useful),
    # "Xtransceiver": ItemData(621, ItemClassification.filler), always have this
    #"God Stone": ItemData(622, ItemClassification.filler),
    "Medal Box": ItemData(627, ItemClassification.progression),
    "DNA Splicers": ItemData(628, ItemClassification.progression),
    "Permit": ItemData(630, ItemClassification.progression),
    "Plasma Card": ItemData(633, ItemClassification.progression),
    "Grubby Hanky": ItemData(634, ItemClassification.progression),
    "Colress MCHN": ItemData(635, ItemClassification.progression),
    "Dropped Item (Yancy)": ItemData(636, ItemClassification.progression),  # does which one you pick up determine who
    "Dropped Item (Curtis)": ItemData(637, ItemClassification.progression),  # calls?
    "Reveal Glass": ItemData(638, ItemClassification.useful),
}

item_groups = {
    "Badges": {"Basic Badge", "Toxic Badge", "Insect Badge", "Bolt Badge",
               "Quake Badge", "Jet Badge", "Legend Badge", "Wave Badge"},
    "HMs": {"HM01 Cut", "HM02 Fly", "HM03 Surf", "HM04 Strength", "HM05 Waterfall", "HM06 Dive"},
    "HM01": {"HM01 Cut"},
    "HM02": {"HM02 Fly"},
    "HM03": {"HM03 Surf"},
    "HM04": {"HM04 Strength"},
    "HM05": {"HM05 Waterfall"},
    "HM06": {"HM06 Dive"},
}

filler_items = {item: all_items[item].code for item in all_items if all_items[item].classification == ItemClassification.filler}
