# Common Items
red_orb = "1000 Red Orbs"
gold_orb = "Gold Orb"
purple_orb_shard = "Purple Orb Shard"
purple_orb = "Purple Orb"
blue_orb_shard = "Blue Orb Shard"
blue_orb = "Blue Orb"
nidhogg_hatchling = "Nidhogg Hatchling"

# Split chapter items
chapter7 = "M7: United Front (Nero/V)"
chapter13 = "M13: Three Warriors (Nero/V/Dante)"

# Nero Upgrades
nero_speed = "Speed (Nero)"
nero_enemy_step = "Enemy Step (Nero)"
nero_air_hike = "Air Hike (Nero)"
nero_more_orbs = "Get More Orbs (Nero)"
nero_trigger_heart = "Trigger Heart (Nero)"
nero_ex_provocation = "EX Provocation (Nero)"
nero_table_hopper = "Progressive Table Hopper (Nero)"
nero_charge_shot = "Progressive Charge Shot (Nero)"
nero_combo_b = "Red Queen B (Nero)"
nero_combo_c = "Red Queen C (Nero)"
nero_combo_d = "Red Queen D (Nero)"
nero_roulette_spin = "Roulette Spin (Nero)"
nero_streak = "Progressive Streak (Nero)"
nero_split = "Split (Nero)"
nero_calibur = "Calibur (Nero)"
nero_shuffle = "Shuffle (Nero)"
nero_hard_way = "Hard Way (Nero)"
nero_payline = "Payline (Nero)"
nero_exceed = "Progressive Exceed (Nero)"
nero_max_act = "MAX-Act (Nero)"
nero_wire_snatch = "Wire Snatch (Nero)"
nero_devil_trigger = "Devil Trigger (Nero)"
nero_flat_top = "Flat Top (Nero)"
nero_showdown = "Showdown (Nero)"
nero_maximum_bet = "Maximum Bet (Nero)"
nero_color_up = "Progressive Color Up (Nero)"
nero_holster = "Progressive Breaker Plus (Nero)"
# Dante Upgrades
dante_speed = "Speed (Dante)"
dante_enemy_step = "Enemy Step (Dante)"
dante_air_hike = "Air Hike (Dante)"
dante_more_orbs = "Get More Orbs (Dante)"
dante_trigger_heart = "Trigger Heart (Dante)"
dante_ex_provocation = "EX Provocation (Dante)"
dante_irregular_full_custom = "Irregular Full Custom (Dante)"
# Guns
dante_charge_shot = "Progressive Ivory & Ebony Charge Shot (Dante)"
dante_coyote_charge_shot = "Progressive Coyote Charge Shot (Dante)"
dante_high_explosive = "High Explosive (Dante)"
dante_man_in_the_red = "The Man In The Red (Dante)"
dante_hat_trick = "Hat Trick (Dante)"
dante_faust = "Progressive Dr. Faust (Dante)"  # First unlocks Faust, 2/3 are upgrades
# Sword
dante_stinger = "Progressive Stinger (Dante)"
dante_million_stab = "Million Stab (Dante)"
dante_drive = "Progressive Drive (Dante)"
dante_swords_formation = "Progressive Swords Formation (Dante)"
# Balrog
dante_rolling_blaze = "Rolling Blaze (Dante)"  # Flush
dante_bantam_revenge = "Bantam Revenge (Dante)"  # White Fang
dante_fly_dragon = "Fly Dragon (Dante)"  # Body Blow
dante_updraft = "Updraft (Dante)"  # Somersault
dante_ignition = "Progressive Ignition (Dante)"
# Cavaliere
dante_cross_line = "Cross Line (Dante)"  # CrossCutter
dante_slipstream = "Slipstream Lv. 2 (Dante)"  # Roller 2
dante_highside = "Highside (Dante)"  # Rising Roller
dante_braking = "Braking (Dante)"  # Drop Roller
# Cerberus
dante_revolver = "Progressive Revolver (Dante)"
dante_crystal = "Crystal (Dante)"
dante_ice_age = "Ice Age (Dante)"
dante_long_revolver = "Long Revolver (Dante)"  # Triplet
dante_thunder_clap = "Thunder Clap (Dante)"  # Thunder Homing
# Styles
dante_trickster = "Progressive Trickster (Dante)"
dante_swordmaster = "Progressive Swordmaster (Dante)"
dante_gunslinger = "Progressive Gunslinger (Dante)"
dante_royalguard = "Progressive Royalguard (Dante)"
# Sin Devil Trigger
dante_sin_stinger = "Sin Stinger (Dante)"  # VortexStinger
dante_sin_inferno = "Sin Inferno (Dante)"  # Inferno
dante_demolition = "Demolition (Dante)"  # Explosion
dante_the_luce = "The Luce (Dante)"  # FeatherLaser
dante_quadruple_s = "Quadruple S (Dante)"  # SSS_Transform
# Weapons
devil_sword_sparda = "Devil Sword Sparda"
devil_sword_dante = "Devil Sword Dante"
balrog = "Balrog"
cavaliere = "Cavaliere"
cerberus = "Cerberus"
coyote = "Coyote"
kalina_ann = "Kalina Ann"
w_kalina_ann = "W Kalina Ann"
dr_faust = "Dr. Faust"
# V Upgrades
v_speed = "Quickplay (V)"
v_enemy_step = "Enemy Step (V)"
v_air_hike = "Air Hike (V)"
v_more_orbs = "More Orbs (V)"
v_trigger_heart = "Trigger Heart (V)"
v_ex_provocation = "EX Provocation (V)"
v_promotion = "Promotion (V)"
v_green_gainer = "Green Gainer (V)"
v_white_gainer = "White Gainer (V)"
v_royal_fork = "Royal Fork (V)"
v_blockage = "Blockage Lv. 2 (V)"
v_round_robin = "Round Robin Lv. 2 (V)"
v_flank_attack = "Flank Attack (V)"
v_double_check = "Double Check (V)"
v_griffon_vim = "Griffon Vim (V)"
v_griffon_vigor = "Griffon Vigor (V)"
v_shadow_combo_b = "Shadow Combo B (V)"
v_shadow_combo_c = "Shadow Combo C (V)"
v_breakthrough = "Breakthrough (V)"
v_hedgehog = "Hedgehog (V)"
v_guillotine = "Guillotine (V)"
v_skewer = "Skewer (V)"
v_shadow_vim = "Shadow Vim (V)"
v_shadow_vigor = "Shadow Vigor (V)"
v_nightmare_combo_b = "Nightmare Combo B (V)"
v_domination = "Domination (V)"
# Vergil
vergil_speed = "Speed (Vergil)"
vergil_enemy_step = "Enemy Step (Vergil)"
vergil_air_hike = "Air Hike (Vergil)"
vergil_more_orbs = "More Orbs (Vergil)"
vergil_trigger_heart = "Trigger Heart (Vergil)"
vergil_ex_provocation = "EX Provocation (Vergil)"
vergil_yamato_combo_b = "Yamato Combo B (Vergil)"
vergil_yamato_combo_c = "Yamato Combo C (Vergil)"
vergil_aerial_rave_b = "Aerial Rave B (Vergil)"
vergil_rapid_slash = "Rapid Slash (Vergil)"
vergil_rising_star = "Rising Star (Vergil)"
vergil_upper_slash = "Upper Slash 2 (Vergil)"
vergil_judgement_cut_end = "Judgement Cut End (Vergil)"
vergil_aerial_cleave = "Aerial Cleave (Vergil)"
vergil_void_slash = "Void Slash (Vergil)"
vergil_beowulf_combo_b = "Beowulf Combo B (Vergil)"
vergil_starfall = "Starfall 2 (Vergil)"
vergil_lunar_phase = "Lunar Phase 2 (Vergil)"
vergil_beast_uppercut = "Beast Uppercut (Vergil)"
vergil_rising_dragon = "Rising Dragon (Vergil)"
vergil_dragon_breaker = "Dragon Breaker (Vergil)"
vergil_flush = "Flush (Vergil)"
vergil_kick13 = "Kick 13 (Vergil)"
vergil_hell_on_earth = "Hell on Earth (Vergil)"
vergil_mirage_edge_combo_b = "Mirage Edge Combo B (Vergil)"
vergil_round_trip = "Round Trip (Vergil)"
vergil_helm_breaker = "Helm Breaker 2 (Vergil)"
vergil_stinger = "Stinger 2 (Vergil)"
vergil_million_stab = "Million Stab (Vergil)"
vergil_drive = "Progressive Drive (Vergil)"
vergil_deep_stinger = "Deep Stinger (Vergil)"
vergil_mirage_blade = "Progressive Mirage Blade (Vergil)"
vergil_spiral_blades = "Spiral Blades (Vergil)"
vergil_storm_blades = "Storm Blades (Vergil)"
vergil_blistering_blades = "Blistering Blades (Vergil)"
vergil_heavyrain_blades = "Heavy Rain Blades (Vergil)"
vergil_trick_dodge = "Trick Dodge (Vergil)"
vergil_trick_down = "Trick Down (Vergil)"
vergil_block = "Block (Vergil)"
