import typing

from BaseClasses import ItemClassification, Item

base_id = 141312111000


class BalatroItem(Item):
    game = "Balatro"


class ItemData(typing.NamedTuple):
    code: int
    name: str
    classification: ItemClassification
    set: str


jokers = {
    # "j_joker": ItemData(base_id + 1, "Joker", ItemClassification.progression, "Joker"),
    "j_greedy_joker": ItemData(base_id + 2, "Greedy Joker", ItemClassification.progression, "Joker"),
    "j_lusty_joker": ItemData(base_id + 3, "Lusty Joker", ItemClassification.progression, "Joker"),
    "j_wrathful_joker": ItemData(base_id + 4, "Wrathful Joker", ItemClassification.progression, "Joker"),
    "j_gluttenous_joker": ItemData(base_id + 5, "Gluttonous Joker", ItemClassification.progression, "Joker"),
    "j_jolly": ItemData(base_id + 6, "Jolly Joker", ItemClassification.progression, "Joker"),
    "j_zany": ItemData(base_id + 7, "Zany Joker", ItemClassification.progression, "Joker"),
    "j_mad": ItemData(base_id + 8, "Mad Joker", ItemClassification.progression, "Joker"),
    "j_crazy": ItemData(base_id + 9, "Crazy Joker", ItemClassification.progression, "Joker"),
    "j_droll": ItemData(base_id + 10, "Droll Joker", ItemClassification.progression, "Joker"),
    "j_sly": ItemData(base_id + 11, "Sly Joker", ItemClassification.progression, "Joker"),
    "j_wily": ItemData(base_id + 12, "Wily Joker", ItemClassification.progression, "Joker"),
    "j_clever": ItemData(base_id + 13, "Clever Joker", ItemClassification.progression, "Joker"),
    "j_devious": ItemData(base_id + 14, "Devious Joker", ItemClassification.progression, "Joker"),
    "j_crafty": ItemData(base_id + 15, "Crafty Joker", ItemClassification.progression, "Joker"),

    "j_half": ItemData(base_id + 16, "Half Joker", ItemClassification.progression, "Joker"),
    "j_stencil": ItemData(base_id + 17, "Joker Stencil", ItemClassification.progression, "Joker"),
    "j_four_fingers": ItemData(base_id + 18, "Four Fingers", ItemClassification.progression, "Joker"),
    "j_mime": ItemData(base_id + 19, "Mime", ItemClassification.progression, "Joker"),
    "j_credit_card": ItemData(base_id + 20, "Credit Card", ItemClassification.progression, "Joker"),
    "j_ceremonial": ItemData(base_id + 21, "Ceremonial Dagger", ItemClassification.progression, "Joker"),
    "j_banner": ItemData(base_id + 22, "Banner", ItemClassification.progression, "Joker"),
    "j_mystic_summit": ItemData(base_id + 23, "Mystic Summit", ItemClassification.progression, "Joker"),
    "j_marble": ItemData(base_id + 24, "Marble Joker", ItemClassification.progression, "Joker"),
    "j_loyalty_card": ItemData(base_id + 25, "Loyalty Card", ItemClassification.progression, "Joker"),
    "j_8_ball": ItemData(base_id + 26, "8 Ball", ItemClassification.progression, "Joker"),
    "j_misprint": ItemData(base_id + 27, "Misprint", ItemClassification.progression, "Joker"),
    "j_dusk": ItemData(base_id + 28, "Dusk", ItemClassification.progression, "Joker"),
    "j_raised_fist": ItemData(base_id + 29, "Raised Fist", ItemClassification.progression, "Joker"),
    "j_chaos": ItemData(base_id + 30, "Chaos the Clown", ItemClassification.progression, "Joker"),

    "j_fibonacci": ItemData(base_id + 31, "Fibonacci", ItemClassification.progression, "Joker"),
    "j_steel_joker": ItemData(base_id + 32, "Steel Joker", ItemClassification.progression, "Joker"),
    "j_scary_face": ItemData(base_id + 33, "Scary Face", ItemClassification.progression, "Joker"),
    "j_abstract": ItemData(base_id + 34, "Abstract Joker", ItemClassification.progression, "Joker"),
    "j_delayed_grat": ItemData(base_id + 35, "Delayed Gratification", ItemClassification.progression, "Joker"),
    "j_hack": ItemData(base_id + 36, "Hack", ItemClassification.progression, "Joker"),
    "j_pareidolia": ItemData(base_id + 37, "Pareidolia", ItemClassification.progression, "Joker"),
    "j_gros_michel": ItemData(base_id + 38, "Gros Michel", ItemClassification.progression, "Joker"),
    "j_even_steven": ItemData(base_id + 39, "Even Steven", ItemClassification.progression, "Joker"),
    "j_odd_todd": ItemData(base_id + 40, "Odd Todd", ItemClassification.progression, "Joker"),
    "j_scholar": ItemData(base_id + 41, "Scholar", ItemClassification.progression, "Joker"),
    "j_business": ItemData(base_id + 42, "Business Card", ItemClassification.progression, "Joker"),
    "j_supernova": ItemData(base_id + 43, "Supernova", ItemClassification.progression, "Joker"),
    "j_ride_the_bus": ItemData(base_id + 44, "Ride the Bus", ItemClassification.progression, "Joker"),
    "j_space": ItemData(base_id + 45, "Space Joker", ItemClassification.progression, "Joker"),

    "j_egg": ItemData(base_id + 46, "Egg", ItemClassification.progression, "Joker"),
    "j_burglar": ItemData(base_id + 47, "Burglar", ItemClassification.progression, "Joker"),
    "j_blackboard": ItemData(base_id + 48, "Blackboard", ItemClassification.progression, "Joker"),
    "j_runner": ItemData(base_id + 49, "Runner", ItemClassification.progression, "Joker"),
    "j_ice_cream": ItemData(base_id + 50, "Ice Cream", ItemClassification.progression, "Joker"),
    "j_dna": ItemData(base_id + 51, "DNA", ItemClassification.progression, "Joker"),
    "j_splash": ItemData(base_id + 52, "Splash", ItemClassification.progression, "Joker"),
    "j_blue_joker": ItemData(base_id + 53, "Blue Joker", ItemClassification.progression, "Joker"),
    "j_sixth_sense": ItemData(base_id + 54, "Sixth Sense", ItemClassification.progression, "Joker"),
    "j_constellation": ItemData(base_id + 55, "Constellation", ItemClassification.progression, "Joker"),
    "j_hiker": ItemData(base_id + 56, "Hiker", ItemClassification.progression, "Joker"),
    "j_faceless": ItemData(base_id + 57, "Faceless Joker", ItemClassification.progression, "Joker"),
    "j_green_joker": ItemData(base_id + 58, "Green Joker", ItemClassification.progression, "Joker"),
    "j_superposition": ItemData(base_id + 59, "Superposition", ItemClassification.progression, "Joker"),
    "j_todo_list": ItemData(base_id + 60, "To Do List", ItemClassification.progression, "Joker"),

    "j_cavendish": ItemData(base_id + 61, "Cavendish", ItemClassification.progression, "Joker"),
    "j_card_sharp": ItemData(base_id + 62, "Card Sharp", ItemClassification.progression, "Joker"),
    "j_red_card": ItemData(base_id + 63, "Red Card", ItemClassification.progression, "Joker"),
    "j_madness": ItemData(base_id + 64, "Madness", ItemClassification.progression, "Joker"),
    "j_square": ItemData(base_id + 65, "Square Joker", ItemClassification.progression, "Joker"),
    "j_seance": ItemData(base_id + 66, "Seance", ItemClassification.progression, "Joker"),
    "j_riff_raff": ItemData(base_id + 67, "Riff-raff", ItemClassification.progression, "Joker"),
    "j_vampire": ItemData(base_id + 68, "Vampire", ItemClassification.progression, "Joker"),
    "j_shortcut": ItemData(base_id + 69, "Shortcut", ItemClassification.progression, "Joker"),
    "j_hologram": ItemData(base_id + 70, "Hologram", ItemClassification.progression, "Joker"),
    "j_vagabond": ItemData(base_id + 71, "Vagabond", ItemClassification.progression, "Joker"),
    "j_baron": ItemData(base_id + 72, "Baron", ItemClassification.progression, "Joker"),
    "j_cloud_9": ItemData(base_id + 73, "Cloud 9", ItemClassification.progression, "Joker"),
    "j_rocket": ItemData(base_id + 74, "Rocket", ItemClassification.progression, "Joker"),
    "j_obelisk": ItemData(base_id + 75, "Obelisk", ItemClassification.progression, "Joker"),

    "j_midas_mask": ItemData(base_id + 76, "Midas Mask", ItemClassification.progression, "Joker"),
    "j_luchador": ItemData(base_id + 77, "Luchador", ItemClassification.progression, "Joker"),
    "j_photograph": ItemData(base_id + 78, "Photograph", ItemClassification.progression, "Joker"),
    "j_gift": ItemData(base_id + 79, "Gift Card", ItemClassification.progression, "Joker"),
    "j_turtle_bean": ItemData(base_id + 80, "Turtle Bean", ItemClassification.progression, "Joker"),
    "j_erosion": ItemData(base_id + 81, "Erosion", ItemClassification.progression, "Joker"),
    "j_reserved_parking": ItemData(base_id + 82, "Reserved Parking", ItemClassification.progression, "Joker"),
    "j_mail": ItemData(base_id + 83, "Mail-In Rebate", ItemClassification.progression, "Joker"),
    "j_to_the_moon": ItemData(base_id + 84, "To the Moon", ItemClassification.progression, "Joker"),
    "j_hallucination": ItemData(base_id + 85, "Hallucination", ItemClassification.progression, "Joker"),
    "j_fortune_teller": ItemData(base_id + 86, "Fortune Teller", ItemClassification.progression, "Joker"),
    "j_juggler": ItemData(base_id + 87, "Juggler", ItemClassification.progression, "Joker"),
    "j_drunkard": ItemData(base_id + 88, "Drunkard", ItemClassification.progression, "Joker"),
    "j_stone": ItemData(base_id + 89, "Stone Joker", ItemClassification.progression, "Joker"),
    "j_golden": ItemData(base_id + 90, "Golden Joker", ItemClassification.progression, "Joker"),

    "j_lucky_cat": ItemData(base_id + 91, "Lucky Cat", ItemClassification.progression, "Joker"),
    "j_baseball": ItemData(base_id + 92, "Baseball Card", ItemClassification.progression, "Joker"),
    "j_bull": ItemData(base_id + 93, "Bull", ItemClassification.progression, "Joker"),
    "j_diet_cola": ItemData(base_id + 94, "Diet Cola", ItemClassification.progression, "Joker"),
    "j_trading": ItemData(base_id + 95, "Trading Card", ItemClassification.progression, "Joker"),
    "j_flash": ItemData(base_id + 96, "Flash Card", ItemClassification.progression, "Joker"),
    "j_popcorn": ItemData(base_id + 97, "Popcorn", ItemClassification.progression, "Joker"),
    "j_trousers": ItemData(base_id + 98, "Spare Trousers", ItemClassification.progression, "Joker"),
    "j_ancient": ItemData(base_id + 99, "Ancient Joker", ItemClassification.progression, "Joker"),
    "j_ramen": ItemData(base_id + 100, "Ramen", ItemClassification.progression, "Joker"),
    "j_walkie_talkie": ItemData(base_id + 101, "Walkie Talkie", ItemClassification.progression, "Joker"),
    "j_selzer": ItemData(base_id + 102, "Seltzer", ItemClassification.progression, "Joker"),
    "j_castle": ItemData(base_id + 103, "Castle", ItemClassification.progression, "Joker"),
    "j_smiley": ItemData(base_id + 104, "Smiley Face", ItemClassification.progression, "Joker"),
    "j_campfire": ItemData(base_id + 105, "Campfire", ItemClassification.progression, "Joker"),

    "j_ticket": ItemData(base_id + 106, "Golden Ticket", ItemClassification.progression, "Joker"),
    "j_mr_bones": ItemData(base_id + 107, "Mr. Bones", ItemClassification.progression, "Joker"),
    "j_acrobat": ItemData(base_id + 108, "Acrobat", ItemClassification.progression, "Joker"),
    "j_sock_and_buskin": ItemData(base_id + 109, "Sock and Buskin", ItemClassification.progression, "Joker"),
    "j_swashbuckler": ItemData(base_id + 110, "Swashbuckler", ItemClassification.progression, "Joker"),
    "j_troubadour": ItemData(base_id + 111, "Troubadour", ItemClassification.progression, "Joker"),
    "j_certificate": ItemData(base_id + 112, "Certificate", ItemClassification.progression, "Joker"),
    "j_smeared": ItemData(base_id + 113, "Smeared Joker", ItemClassification.progression, "Joker"),
    "j_throwback": ItemData(base_id + 114, "Throwback", ItemClassification.progression, "Joker"),
    "j_hanging_chad": ItemData(base_id + 115, "Hanging Chad", ItemClassification.progression, "Joker"),
    "j_rough_gem": ItemData(base_id + 116, "Rough Gem", ItemClassification.progression, "Joker"),
    "j_bloodstone": ItemData(base_id + 117, "Bloodstone", ItemClassification.progression, "Joker"),
    "j_arrowhead": ItemData(base_id + 118, "Arrowhead", ItemClassification.progression, "Joker"),
    "j_onyx_agate": ItemData(base_id + 119, "Onyx Agate", ItemClassification.progression, "Joker"),
    "j_glass": ItemData(base_id + 120, "Glass Joker", ItemClassification.progression, "Joker"),

    "j_ring_master": ItemData(base_id + 121, "Showman", ItemClassification.progression, "Joker"),
    "j_flower_pot": ItemData(base_id + 122, "Flower Pot", ItemClassification.progression, "Joker"),
    "j_blueprint": ItemData(base_id + 123, "Blueprint", ItemClassification.progression, "Joker"),
    "j_wee": ItemData(base_id + 124, "Wee Joker", ItemClassification.progression, "Joker"),
    "j_merry_andy": ItemData(base_id + 125, "Merry Andy", ItemClassification.progression, "Joker"),
    "j_oops": ItemData(base_id + 126, "Oops! All 6s", ItemClassification.progression, "Joker"),
    "j_idol": ItemData(base_id + 127, "The Idol", ItemClassification.progression, "Joker"),
    "j_seeing_double": ItemData(base_id + 128, "Seeing Double", ItemClassification.progression, "Joker"),
    "j_matador": ItemData(base_id + 129, "Matador", ItemClassification.progression, "Joker"),
    "j_hit_the_road": ItemData(base_id + 130, "Hit the Road", ItemClassification.progression, "Joker"),
    "j_duo": ItemData(base_id + 131, "The Duo", ItemClassification.progression, "Joker"),
    "j_trio": ItemData(base_id + 132, "The Trio", ItemClassification.progression, "Joker"),
    "j_family": ItemData(base_id + 133, "The Family", ItemClassification.progression, "Joker"),
    "j_order": ItemData(base_id + 134, "The Order", ItemClassification.progression, "Joker"),
    "j_tribe": ItemData(base_id + 135, "The Tribe", ItemClassification.progression, "Joker"),

    "j_stuntman": ItemData(base_id + 136, "Stuntman", ItemClassification.progression, "Joker"),
    "j_invisible": ItemData(base_id + 137, "Invisible Joker", ItemClassification.progression, "Joker"),
    "j_brainstorm": ItemData(base_id + 138, "Brainstorm", ItemClassification.progression, "Joker"),
    "j_satellite": ItemData(base_id + 139, "Satellite", ItemClassification.progression, "Joker"),
    "j_shoot_the_moon": ItemData(base_id + 140, "Shoot the Moon", ItemClassification.progression, "Joker"),
    "j_drivers_license": ItemData(base_id + 141, "Driver's License", ItemClassification.progression, "Joker"),
    "j_cartomancer": ItemData(base_id + 142, "Cartomancer", ItemClassification.progression, "Joker"),
    "j_astronomer": ItemData(base_id + 143, "Astronomer", ItemClassification.progression, "Joker"),
    "j_burnt": ItemData(base_id + 144, "Burnt Joker", ItemClassification.progression, "Joker"),
    "j_bootstraps": ItemData(base_id + 145, "Bootstraps", ItemClassification.progression, "Joker"),
    "j_caino": ItemData(base_id + 146, "Caino", ItemClassification.progression, "Joker"),
    "j_triboulet": ItemData(base_id + 147, "Triboulet", ItemClassification.progression, "Joker"),
    "j_yorick": ItemData(base_id + 148, "Yorick", ItemClassification.progression, "Joker"),
    "j_chicot": ItemData(base_id + 149, "Chicot", ItemClassification.progression, "Joker"),
    "j_perkeo": ItemData(base_id + 150, "Perkeo", ItemClassification.progression, "Joker"),
}

tarots = {
    # "c_fool": ItemData(base_id + 1, "The Fool", ItemClassification.progression, "Tarot"),
    "c_magician": ItemData(base_id + 151, "The Magician", ItemClassification.progression, "Tarot"),
    "c_high_priestess": ItemData(base_id + 152, "The High Priestess", ItemClassification.progression, "Tarot"),
    "c_empress": ItemData(base_id + 153, "The Empress", ItemClassification.progression, "Tarot"),
    "c_emperor": ItemData(base_id + 154, "The Emperor", ItemClassification.progression, "Tarot"),
    "c_heirophant": ItemData(base_id + 155, "The Hierophant", ItemClassification.progression, "Tarot"),
    "c_lovers": ItemData(base_id + 156, "The Lovers", ItemClassification.progression, "Tarot"),
    "c_chariot": ItemData(base_id + 157, "The Chariot", ItemClassification.progression, "Tarot"),
    "c_justice": ItemData(base_id + 158, "Justice", ItemClassification.progression, "Tarot"),
    "c_hermit": ItemData(base_id + 159, "The Hermit", ItemClassification.progression, "Tarot"),
    "c_wheel_of_fortune": ItemData(base_id + 160, "The Wheel of Fortune", ItemClassification.progression, "Tarot"),
    "c_strength": ItemData(base_id + 161, "Strength", ItemClassification.progression, "Tarot"),
    "c_hanged_man": ItemData(base_id + 162, "The Hanged Man", ItemClassification.progression, "Tarot"),
    "c_death": ItemData(base_id + 163, "Death", ItemClassification.progression, "Tarot"),
    "c_temperance": ItemData(base_id + 164, "Temperance", ItemClassification.progression, "Tarot"),
    "c_devil": ItemData(base_id + 165, "The Devil", ItemClassification.progression, "Tarot"),
    "c_tower": ItemData(base_id + 166, "The Tower", ItemClassification.progression, "Tarot"),
    "c_star": ItemData(base_id + 167, "The Star", ItemClassification.progression, "Tarot"),
    "c_moon": ItemData(base_id + 168, "The Moon", ItemClassification.progression, "Tarot"),
    "c_sun": ItemData(base_id + 169, "The Sun", ItemClassification.progression, "Tarot"),
    "c_judgement": ItemData(base_id + 170, "Judgement", ItemClassification.progression, "Tarot"),
    "c_world": ItemData(base_id + 171, "The World", ItemClassification.progression, "Tarot"),
}

item_table = {
    "Random Consumable": ItemData(base_id + 1, "Random Consumable", ItemClassification.filler, ""),
    **jokers,
    **tarots,
}
