import typing

from BaseClasses import ItemClassification


class ItemData(typing.NamedTuple):
    local_id: int
    name: str
    classification: ItemClassification
    set: str


jokers = {
    ItemData(1, "Joker", ItemClassification.progression, "Joker"),
    ItemData(2, "Greedy Joker", ItemClassification.progression, "Joker"),
    ItemData(3, "Lusty Joker", ItemClassification.progression, "Joker"),
    ItemData(4, "Wrathful Joker", ItemClassification.progression, "Joker"),
    ItemData(5, "Gluttonous Joker", ItemClassification.progression, "Joker"),
    ItemData(6, "Jolly Joker", ItemClassification.progression, "Joker"),
    ItemData(7, "Zany Joker", ItemClassification.progression, "Joker"),
    ItemData(8, "Mad Joker", ItemClassification.progression, "Joker"),
    ItemData(9, "Crazy Joker", ItemClassification.progression, "Joker"),
    ItemData(10, "Droll Joker", ItemClassification.progression, "Joker"),
    ItemData(11, "Sly Joker", ItemClassification.progression, "Joker"),
    ItemData(12, "Wily Joker", ItemClassification.progression, "Joker"),
    ItemData(13, "Clever Joker", ItemClassification.progression, "Joker"),
    ItemData(14, "Devious Joker", ItemClassification.progression, "Joker"),
    ItemData(15, "Crafty Joker", ItemClassification.progression, "Joker"),

    ItemData(16, "Half Joker", ItemClassification.progression, "Joker"),
    ItemData(17, "Joker Stencil", ItemClassification.progression, "Joker"),
    ItemData(18, "Four Fingers", ItemClassification.progression, "Joker"),
    ItemData(19, "Mime", ItemClassification.progression, "Joker"),
    ItemData(20, "Credit Card", ItemClassification.progression, "Joker"),
    ItemData(21, "Ceremonial Dagger", ItemClassification.progression, "Joker"),
    ItemData(22, "Banner", ItemClassification.progression, "Joker"),
    ItemData(23, "Mystic Summit", ItemClassification.progression, "Joker"),
    ItemData(24, "Marble Joker", ItemClassification.progression, "Joker"),
    ItemData(25, "Loyalty Card", ItemClassification.progression, "Joker"),
    ItemData(26, "8 Ball", ItemClassification.progression, "Joker"),
    ItemData(27, "Misprint", ItemClassification.progression, "Joker"),
    ItemData(28, "Dusk", ItemClassification.progression, "Joker"),
    ItemData(29, "Raised Fist", ItemClassification.progression, "Joker"),
    ItemData(30, "Chaos the Clown", ItemClassification.progression, "Joker"),
    ItemData(31, "Fibonacci", ItemClassification.progression, "Joker"),
    ItemData(32, "Steel Joker", ItemClassification.progression, "Joker"),
    ItemData(33, "Scary Face", ItemClassification.progression, "Joker"),
    ItemData(34, "Abstract Joker", ItemClassification.progression, "Joker"),
    ItemData(35, "Delayed Gratification", ItemClassification.progression, "Joker"),
    ItemData(36, "Hack", ItemClassification.progression, "Joker"),
    ItemData(37, "Pareidolia", ItemClassification.progression, "Joker"),
    ItemData(38, "Gros Michel", ItemClassification.progression, "Joker"),
    ItemData(39, "Even Steven", ItemClassification.progression, "Joker"),
    ItemData(40, "Odd Todd", ItemClassification.progression, "Joker"),
    ItemData(41, "Scholar", ItemClassification.progression, "Joker"),
    ItemData(42, "Business Card", ItemClassification.progression, "Joker"),
    ItemData(43, "Supernova", ItemClassification.progression, "Joker"),
    ItemData(44, "Ride the Bus", ItemClassification.progression, "Joker"),
    ItemData(45, "Space Joker", ItemClassification.progression, "Joker"),
    ItemData(46, 'Egg', ItemClassification.progression, "Joker"),
    ItemData(47, 'Burglar', ItemClassification.progression, "Joker"),
    ItemData(48, 'Blackboard', ItemClassification.progression, "Joker"),
    ItemData(49, 'Runner', ItemClassification.progression, "Joker"),
    ItemData(50, 'Ice Cream', ItemClassification.progression, "Joker"),
    ItemData(51, 'DNA', ItemClassification.progression, "Joker"),
    ItemData(52, 'Splash', ItemClassification.progression, "Joker"),
    ItemData(53, 'Blue Joker', ItemClassification.progression, "Joker"),
    ItemData(54, 'Sixth Sense', ItemClassification.progression, "Joker"),
    ItemData(55, 'Constellation', ItemClassification.progression, "Joker"),
    ItemData(56, 'Hiker', ItemClassification.progression, "Joker"),
    ItemData(57, 'Faceless Joker', ItemClassification.progression, "Joker"),
    ItemData(58, 'Green Joker', ItemClassification.progression, "Joker"),
    ItemData(59, 'Superposition', ItemClassification.progression, "Joker"),
    ItemData(60, 'To Do List', ItemClassification.progression, "Joker"),

    ItemData(61, "Cavendish", ItemClassification.progression, "Joker"),
    ItemData(62, "Card Sharp", ItemClassification.progression, "Joker"),
    ItemData(63, "Red Card", ItemClassification.progression, "Joker"),
    ItemData(64, "Madness", ItemClassification.progression, "Joker"),
    ItemData(65, "Square Joker", ItemClassification.progression, "Joker"),
    ItemData(66, "Seance", ItemClassification.progression, "Joker"),
    ItemData(67, "Riff-raff", ItemClassification.progression, "Joker"),
    ItemData(68, "Vampire", ItemClassification.progression, "Joker"),
    ItemData(69, "Shortcut", ItemClassification.progression, "Joker"),
    ItemData(70, "Hologram", ItemClassification.progression, "Joker"),
    ItemData(71, "Vagabond", ItemClassification.progression, "Joker"),
    ItemData(72, "Baron", ItemClassification.progression, "Joker"),
    ItemData(73, "Cloud 9", ItemClassification.progression, "Joker"),
    ItemData(74, "Rocket", ItemClassification.progression, "Joker"),
    ItemData(75, "Obelisk", ItemClassification.progression, "Joker"),

    ItemData(76, "Midas Mask", ItemClassification.progression, "Joker"),
    ItemData(77, "Luchador", ItemClassification.progression, "Joker"),
    ItemData(78, "Photograph", ItemClassification.progression, "Joker"),
    ItemData(79, "Gift Card", ItemClassification.progression, "Joker"),
    ItemData(80, "Turtle Bean", ItemClassification.progression, "Joker"),
    ItemData(81, "Erosion", ItemClassification.progression, "Joker"),
    ItemData(82, "Reserved Parking", ItemClassification.progression, "Joker"),
    ItemData(83, "Mail-In Rebate", ItemClassification.progression, "Joker"),
    ItemData(84, "To the Moon", ItemClassification.progression, "Joker"),
    ItemData(85, "Hallucination", ItemClassification.progression, "Joker"),
    ItemData(86, "Fortune Teller", ItemClassification.progression, "Joker"),
    ItemData(87, "Juggler", ItemClassification.progression, "Joker"),
    ItemData(88, "Drunkard", ItemClassification.progression, "Joker"),
    ItemData(89, "Stone Joker", ItemClassification.progression, "Joker"),
    ItemData(90, "Golden Joker", ItemClassification.progression, "Joker"),

    ItemData(91, "Lucky Cat", ItemClassification.progression, "Joker"),
    ItemData(92, "Baseball Card", ItemClassification.progression, "Joker"),
    ItemData(93, "Bull", ItemClassification.progression, "Joker"),
    ItemData(94, "Diet Cola", ItemClassification.progression, "Joker"),
    ItemData(95, "Trading Card", ItemClassification.progression, "Joker"),
    ItemData(96, "Flash Card", ItemClassification.progression, "Joker"),
    ItemData(97, "Popcorn", ItemClassification.progression, "Joker"),
    ItemData(98, "Spare Trousers", ItemClassification.progression, "Joker"),
    ItemData(99, "Ancient Joker", ItemClassification.progression, "Joker"),
    ItemData(100, "Ramen", ItemClassification.progression, "Joker"),
    ItemData(101, "Walkie Talkie", ItemClassification.progression, "Joker"),
    ItemData(102, "Seltzer", ItemClassification.progression, "Joker"),
    ItemData(103, "Castle", ItemClassification.progression, "Joker"),
    ItemData(104, "Smiley Face", ItemClassification.progression, "Joker"),
    ItemData(105, "Campfire", ItemClassification.progression, "Joker"),

    ItemData(106, "Golden Ticket", ItemClassification.progression, "Joker"),
    ItemData(107, "Mr. Bones", ItemClassification.progression, "Joker"),
    ItemData(108, "Acrobat", ItemClassification.progression, "Joker"),
    ItemData(109, "Sock and Buskin", ItemClassification.progression, "Joker"),
    ItemData(110, "Swashbuckler", ItemClassification.progression, "Joker"),
    ItemData(111, "Troubadour", ItemClassification.progression, "Joker"),
    ItemData(112, "Certificate", ItemClassification.progression, "Joker"),
    ItemData(113, "Smeared Joker", ItemClassification.progression, "Joker"),
    ItemData(114, "Throwback", ItemClassification.progression, "Joker"),
    ItemData(115, "Hanging Chad", ItemClassification.progression, "Joker"),
    ItemData(116, "Rough Gem", ItemClassification.progression, "Joker"),
    ItemData(117, "Bloodstone", ItemClassification.progression, "Joker"),
    ItemData(118, "Arrowhead", ItemClassification.progression, "Joker"),
    ItemData(119, "Onyx Agate", ItemClassification.progression, "Joker"),
    ItemData(120, "Glass Joker", ItemClassification.progression, "Joker"),

    ItemData(121, "Showman", ItemClassification.progression, "Joker"),
    ItemData(122, "Flower Pot", ItemClassification.progression, "Joker"),
    ItemData(123, "Blueprint", ItemClassification.progression, "Joker"),
    ItemData(124, "Wee Joker", ItemClassification.progression, "Joker"),
    ItemData(125, "Merry Andy", ItemClassification.progression, "Joker"),
    ItemData(126, "Oops! All 6s", ItemClassification.progression, "Joker"),
    ItemData(127, "The Idol", ItemClassification.progression, "Joker"),
    ItemData(128, "Seeing Double", ItemClassification.progression, "Joker"),
    ItemData(129, "Matador", ItemClassification.progression, "Joker"),
    ItemData(130, "Hit the Road", ItemClassification.progression, "Joker"),
    ItemData(131, "The Duo", ItemClassification.progression, "Joker"),
    ItemData(132, "The Trio", ItemClassification.progression, "Joker"),
    ItemData(133, "The Family", ItemClassification.progression, "Joker"),
    ItemData(134, "The Order", ItemClassification.progression, "Joker"),
    ItemData(135, "The Tribe", ItemClassification.progression, "Joker"),
    ItemData(136, "Stuntman", ItemClassification.progression, "Joker"),
    ItemData(137, "Invisible Joker", ItemClassification.progression, "Joker"),
    ItemData(138, "Brainstorm", ItemClassification.progression, "Joker"),
    ItemData(139, "Satellite", ItemClassification.progression, "Joker"),
    ItemData(140, "Shoot the Moon", ItemClassification.progression, "Joker"),
    ItemData(141, "Driver", ItemClassification.progression, "Joker"),
    ItemData(142, "Cartomancer", ItemClassification.progression, "Joker"),
    ItemData(143, "Astronomer", ItemClassification.progression, "Joker"),
    ItemData(144, "Burnt Joker", ItemClassification.progression, "Joker"),
    ItemData(145, "Bootstraps", ItemClassification.progression, "Joker"),
    ItemData(146, "Caino", ItemClassification.progression, "Joker"),
    ItemData(147, "Triboulet", ItemClassification.progression, "Joker"),
    ItemData(148, "Yorick", ItemClassification.progression, "Joker"),
    ItemData(149, "Chicot", ItemClassification.progression, "Joker"),
    ItemData(150, "Perkeo", ItemClassification.progression, "Joker"),
}

tarots = {
    ItemData(1, "The Fool", ItemClassification.progression, "Tarot"),
    ItemData(2, "The Magician", ItemClassification.progression, "Tarot"),
    ItemData(3, "The High Priestess", ItemClassification.progression, "Tarot"),
    ItemData(4, "The Empress", ItemClassification.progression, "Tarot"),
    ItemData(5, "The Emperor", ItemClassification.progression, "Tarot"),
    ItemData(6, "The Hierophant", ItemClassification.progression, "Tarot"),
    ItemData(7, "The Lovers", ItemClassification.progression, "Tarot"),
    ItemData(8, "The Chariot", ItemClassification.progression, "Tarot"),
    ItemData(9, "Justice", ItemClassification.progression, "Tarot"),
    ItemData(10, "The Hermit", ItemClassification.progression, "Tarot"),
    ItemData(11, "The Wheel of Fortune", ItemClassification.progression, "Tarot"),
    ItemData(12, "Strength", ItemClassification.progression, "Tarot"),
    ItemData(13, "The Hanged Man", ItemClassification.progression, "Tarot"),
    ItemData(14, "Death", ItemClassification.progression, "Tarot"),
    ItemData(15, "Temperance", ItemClassification.progression, "Tarot"),
    ItemData(16, "The Devil", ItemClassification.progression, "Tarot"),
    ItemData(17, "The Tower", ItemClassification.progression, "Tarot"),
    ItemData(18, "The Star", ItemClassification.progression, "Tarot"),
    ItemData(19, "The Moon", ItemClassification.progression, "Tarot"),
    ItemData(20, "The Sun", ItemClassification.progression, "Tarot"),
    ItemData(21, "Judgement", ItemClassification.progression, "Tarot"),
    ItemData(22, "The World", ItemClassification.progression, "Tarot"),
}