# Spring Breeze
sb_whispy = "Spring Breeze - Whispy Woods"
sb_lololo = "Spring Breeze - Lololo & Lalala"
sb_kracko = "Spring Breeze - Kracko"
sb_dedede = "Spring Breeze - King Dedede"
sb_complete = "Spring Breeze - Castle Dedede"

# Dyna Blade
db_stage_1 = "Dyna Blade - Peanut Plains"
db_stage_2 = "Dyna Blade - Mallow Castle"
db_stage_3 = "Dyna Blade - Cocoa Cave"
db_stage_4 = "Dyna Blade - Candy Mountain"
db_stage_5 = "Dyna Blade - Dyna Blade's Nest"
db_complete = "Dyna Blade - Dyna Blade"
db_switch_1 = "Dyna Blade - Switch 1"
db_switch_2 = "Dyna Blade - Switch 2"
db_iron_mam = "Dyna Blade - Iron Mam"

# Gourmet Race
gr_stage_1 = "Gourmet Race - Win Round 1"
gr_stage_2 = "Gourmet Race - Win Round 2"
gr_stage_3 = "Gourmet Race - Win Round 3"
gr_complete = "Gourmet Race - Results"

# The Great Cave Offensive
tgco_fatty_whale = "The Great Cave Offensive - Fatty Whale"
tgco_virus = "The Great Cave Offensive - Computer Virus"
tgco_chameleon = "The Great Cave Offensive - Chameleo Arm"
tgco_wham_bam = "The Great Cave Offensive - Wham Bam Rock"
tgco_complete = "The Great Cave Offensive - Cave Exit"

# Treasures
tgco_treasure_1 = "Sub-Tree - Gold Medal"
tgco_treasure_2 = "Sub-Tree - Gold Coin"
tgco_treasure_3 = "Sub-Tree - Whip"
tgco_treasure_4 = "Sub-Tree - Crystal Ball"
tgco_treasure_5 = "Sub-Tree - Lucky Cat"
tgco_treasure_6 = "Sub-Tree - Seiryu Sword"
tgco_treasure_7 = "Sub-Tree - Screw Attack"
tgco_treasure_8 = "Sub-Tree - Echigo Candy"
tgco_treasure_9 = "Sub-Tree - Zebra Mask"
tgco_treasure_10 = "Sub-Tree - Star Stone"
tgco_treasure_11 = "Sub-Tree - Beast's Fang"
tgco_treasure_12 = "Sub-Tree - Bandanna"
tgco_treasure_13 = "Sub-Tree - Springtime"
tgco_treasure_14 = "Crystal - Dime"
tgco_treasure_15 = "Crystal - Glass Slippers"
tgco_treasure_16 = "Crystal - Goblet"
tgco_treasure_17 = "Crystal - Saucepan"
tgco_treasure_18 = "Crystal - Brass Knuckle"
tgco_treasure_19 = "Crystal - Amber Rose"
tgco_treasure_20 = "Crystal - Fish Fossil"
tgco_treasure_21 = "Crystal - Beast Fossil"
tgco_treasure_22 = "Crystal - Nunchuks"
tgco_treasure_23 = "Crystal - Bucket"
tgco_treasure_24 = "Crystal - Summertime"
tgco_treasure_25 = "Crystal - 100-Dollar Coin"
tgco_treasure_26 = "Crystal - Ancient Gem"
tgco_treasure_27 = "Crystal - Falcon Helmet"
tgco_treasure_28 = "Crystal - Dud"
tgco_treasure_29 = "Crystal - Truth Mirror"
tgco_treasure_30 = "Old Tower - Star Tiara"
tgco_treasure_31 = "Old Tower - Turtle Shell"
tgco_treasure_32 = "Old Tower - Falchion"
tgco_treasure_33 = "Old Tower - Warrior Shield"
tgco_treasure_34 = "Old Tower - Unicorn's Horn"
tgco_treasure_35 = "Old Tower - Autumntime"
tgco_treasure_36 = "Old Tower - Rice Bowl"
tgco_treasure_37 = "Old Tower - Tut's Mask"
tgco_treasure_38 = "Old Tower - Mr. Saturn"
tgco_treasure_39 = "Old Tower - Armor"
tgco_treasure_40 = "Old Tower - Treasure Box"
tgco_treasure_41 = "Old Tower - Mannequin"
tgco_treasure_42 = "Old Tower - Gold Crown"
tgco_treasure_43 = "Old Tower - King's Cape"
tgco_treasure_44 = "Old Tower - Model Ship"
tgco_treasure_45 = "Old Tower - Sun Ring"
tgco_treasure_46 = "Garden - Wintertime"
tgco_treasure_47 = "Garden - Katana"
tgco_treasure_48 = "Garden - Charm"
tgco_treasure_49 = "Garden - Xmas Tree"
tgco_treasure_50 = "Garden - Kong's Barrel"
tgco_treasure_51 = "Garden - Ramia's Scale"
tgco_treasure_52 = "Garden - Shiny Bamboo"
tgco_treasure_53 = "Garden - Tire"
tgco_treasure_54 = "Garden - Spirit Charm"
tgco_treasure_55 = "Garden - Pegasus Wing"
tgco_treasure_56 = "Garden - Raccoon Doll"
tgco_treasure_57 = "Garden - Shell Whistle"
tgco_treasure_58 = "Garden - Orichalcum"
tgco_treasure_59 = "Garden - Platinum Ring"
tgco_treasure_60 = "Garden - Triforce"

# Revenge of Meta Knight
romk_chapter_1 = "Revenge of Meta Knight - Chapter 1"
romk_chapter_2 = "Revenge of Meta Knight - Chapter 2"
romk_chapter_3 = "Revenge of Meta Knight - Chapter 3" # needs Fire
romk_chapter_4 = "Revenge of Meta Knight - Chapter 4"
romk_chapter_5 = "Revenge of Meta Knight - Chapter 5"
romk_chapter_6 = "Revenge of Meta Knight - Chapter 6"
romk_chapter_7 = "Revenge of Meta Knight - Chapter 7"
romk_complete = "Revenge of Meta Knight - Halberd's Helm" # doesn't require Wheel (its a partner)

# Milky Way Wishes
mww_floria = "Floria - Twin Woods"
mww_cutter = "Floria - Cutter Essence"
mww_fighter = "Floria - Fighter Essence"
mww_ice = "Floria - Ice Essence"
mww_aqualiss = "Aqualiss - Fatty Whale"
mww_beam = "Aqualiss - Beam Essence"
mww_parasol = "Aqualiss - Parasol Essence"
mww_sword = "Aqualiss - Sword Essence"
mww_skyhigh = "Skyhigh - Kracko"
mww_jet = "Skyhigh - Jet Essence"
mww_wheel = "Skyhigh - Wheel Essence"
mww_wing = "Skyhigh - Wing Essence"
mww_hotbeat = "Hotbeat - Chameleo Arm"
mww_fire = "Hotbeat - Fire Essence"
mww_suplex = "Hotbeat - Suplex Essence"
mww_cavios = "Cavios - Wham Bam Rock"
mww_bomb = "Cavios - Bomb Essence"
mww_hammer = "Cavios - Hammer Essence"
mww_stone = "Cavios - Stone Essence"
mww_mecheye = "Mecheye - Heavy Lobster"
mww_plasma = "Mecheye - Plasma Essence"
mww_yoyo = "Mecheye - Yoyo Essence"
mww_halfmoon = "Halfmoon - Computer Virus"
mww_mirror = "Halfmoon - Mirror Essence"
mww_ninja = "Halfmoon - Ninja Essence"
mww_copy = "??? - Copy Essence"
mww_complete = "Galactic Nova"

# The Arena
arena_1 = "The Arena - 1 Straight Win"
arena_2 = "The Arena - 2 Straight Wins"
arena_3 = "The Arena - 3 Straight Wins"
arena_4 = "The Arena - 4 Straight Wins"
arena_5 = "The Arena - 5 Straight Wins"
arena_6 = "The Arena - 6 Straight Wins"
arena_7 = "The Arena - 7 Straight Wins"
arena_8 = "The Arena - 8 Straight Wins"
arena_9 = "The Arena - 9 Straight Wins"
arena_10 = "The Arena - 10 Straight Wins"
arena_11 = "The Arena - 11 Straight Wins"
arena_12 = "The Arena - 12 Straight Wins"
arena_13 = "The Arena - 13 Straight Wins"
arena_14 = "The Arena - 14 Straight Wins"
arena_15 = "The Arena - 15 Straight Wins"
arena_16 = "The Arena - 16 Straight Wins"
arena_17 = "The Arena - 17 Straight Wins"
arena_18 = "The Arena - 18 Straight Wins"
arena_19 = "The Arena - 19 Straight Wins"
arena_complete = "The Arena - 20 Straight Wins"

# Begin Consumables/Essences
sb_gg_maxim = "Green Greens - Maxim Tomato"
sb_gg_1up = "Green Greens - 1-Up"
sb_fl_1up = "Float Islands - 1-Up"
sb_fl_candy = "Float Islands - Invincibility Candy"
sb_bc_1up = "Bubbly Clouds - 1-Up"
sb_bc_maxim = "Bubbly Clouds - Maxim Tomato"
sb_bc_1up_moon = "Bubbly Clouds - 1-Up (Secret)"

db_pp_1up_1 = "Peanut Plains - 1-Up (1)"
db_pp_maxim_1 = "Peanut Plains - Maxim Tomato (1)"
db_pp_sword = "Peanut Plains - Sword Essence"
db_pp_maxim_2 = "Peanut Plains - Maxim Tomato (2)"
db_pp_1up_2 = "Peanut Plains - 1-Up (2)"
db_pp_candy = "Peanut Plains - Invincibility Candy"
db_pp_maxim_3 = "Peanut Plains - Maxim Tomato (3)"

db_mc_1up_1 = "Mallow Castle - 1-Up (1)"
db_mc_wheel = "Mallow Castle - Wheel Essence"
db_mc_maxim_1 = "Mallow Castle - Maxim Tomato (1)"
db_mc_1up_2 = "Mallow Castle - 1-Up (2)"
db_mc_1up_3 = "Mallow Castle - 1-Up (Demolished Left)"
db_mc_1up_4 = "Mallow Castle - 1-Up (Demolished Middle)"
db_mc_1up_5 = "Mallow Castle - 1-Up (Demolished Right)"

db_b1_maxim_l = "Dyna Blade Bonus 1 - Maxim Tomato (Left)"
db_b1_maxim_r = "Dyna Blade Bonus 1 - Maxim Tomato (Right)"
db_b1_beam = "Dyna Blade Bonus 1 - Beam Essence"
db_b1_fire = "Dyna Blade Bonus 1 - Fire Essence"
db_b1_mirror = "Dyna Blade Bonus 1 - Mirror Essence"
db_b1_fighter = "Dyna Blade Bonus 1 - Fighter Essence"
db_b1_cutter = "Dyna Blade Bonus 1 - Cutter Essence"
db_b1_plasma = "Dyna Blade Bonus 1 - Plasma Essence"
db_b1_ninja = "Dyna Blade Bonus 1 - Ninja Essence"
db_b1_sword = "Dyna Blade Bonus 1 - Sword Essence"
db_b1_bomb = "Dyna Blade Bonus 1 - Bomb Essence"
db_b1_hammer = "Dyna Blade Bonus 1 - Hammer Essence"

db_cc_maxim_1 = "Cocoa Cave - Maxim Tomato"
db_cc_1up_1 = "Cocoa Cave - 1-Up (1)"
db_cc_1up_2 = "Cocoa Cave - 1-Up (2)"

db_cm_1up_1 = "Candy Mountain - 1-Up (Upper)"
db_cm_hammer = "Candy Mountain - Hammer Essence"
db_cm_1up_2 = "Candy Mountain - 1-Up (Fire 1)"
db_cm_1up_3 = "Candy Mountain - 1-Up (Fire 2)"
db_cm_1up_4 = "Candy Mountain - 1-Up (Fire 3)"
db_cm_candy = "Candy Mountain - Invincibility Candy"
db_cm_maxim_1 = "Candy Mountain - Maxim Tomato (1)"
db_cm_maxim_2 = "Candy Mountain - Maxim Tomato (2)"
db_cm_1up_5 = "Candy Mountain - 1-Up (5)"
db_cm_copy = "Candy Mountain - Copy Essence"
db_cm_1up_6 = "Candy Mountain - 1-Up (6)"
db_cm_maxim_3 = "Candy Mountain - Maxim Tomato (3)"

db_b2_wheel = "Dyna Blade Bonus 2 - Wheel Essence"
db_b2_yoyo = "Dyna Blade Bonus 2 - Yo-Yo Essence"
db_b2_wing = "Dyna Blade Bonus 2 - Wing Essence"
db_b2_stone = "Dyna Blade Bonus 2 - Stone Essence"
db_b2_parasol = "Dyna Blade Bonus 2 - Parasol Essence"
db_b2_jet = "Dyna Blade Bonus 2 - Jet Essence"
db_b2_ice = "Dyna Blade Bonus 2 - Ice Essence"
db_b2_suplex = "Dyna Blade Bonus 2 - Suplex Essence"
db_b2_copy = "Dyna Blade Bonus 2 - Copy Essence"
db_b2_maxim = "Dyna Blade Bonus 2 - Maxim Tomato"

gr_jet = "Gourmet Race 3 - Jet Essence"
gr_parasol = "Gourmet Race 3 - Parasol Essence"
gr_ninja = "Gourmet Race 3 - Ninja Essence"
gr_wing = "Gourmet Race 3 - Wing Essence"
gr_wheel = "Gourmet Race 3 - Wheel Essence"
